feat: reposition input forms
lablup/backend.ai-webui pull request #1009
Opened 2021-05-27 09:13 UTC by Sujin-Kim1

- Relocate the dialogue content of backend-ai-session-launcher.ts.
- If you want to test it, you must change the part of the backend-ai-summary-view.ts or backend-ai-session-view.ts that uses the session lacher.

Issues that have not yet been completed
- Add carousel libraries or pagination features.

2021-05-28 08:34 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +          --component-max-height: 640px;
We need to specify the maximum size of the dialog to provide a better user experience in the mobile environment. Therefore, I added the maximum height of the session-launcher dialog.

2021-05-28 08:38 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +          width: 370px; // default width
I added the width of `mwc-list-item`, which is the children element of `mwc-select` and `mwc-list`. It follows the width of those elements.
please keep in mind that when you added `fixedMenuPosition` attribute in `mwc-select`, this style setting becomes necessary.
(ref: [`mwc-select` documentation](https://github.com/material-components/material-components-web-components/tree/master/packages/select))

2021-05-28 08:40 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +            <mwc-select id="environment" icon="code" label="${_t('session.launcher.Environments')}" required fixedMenuPosition
When you add `fixedMenuPosition` attribute in the `mwc-select` element, item elements will be exposed in front of the dialog if `mwc-select` is inside of `mwc-dialog`.

2021-05-28 08:40 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +            <mwc-select id="version" icon="architecture" label="${_t('session.launcher.Version')}" required fixedMenuPosition>
Same explanation from above.

2021-05-28 08:40 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                          icon="storage" required fixedMenuPosition
Same explanation from above.

2021-05-28 08:41 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                          icon="dashboard_customize" required fixedMenuPosition>
Same explanation from above.

2021-05-28 08:41 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                          icon="account_tree" fixedMenuPosition
Same explanation from above.

2021-05-28 08:41 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                <mwc-select id="owner-accesskey" label="${_t('session.launcher.OwnerAccessKey')}" icon="vpn_key" fixedMenuPosition>
Same explanation from above.

2021-05-28 08:41 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                  <mwc-select id="owner-group" label="${_t('session.launcher.OwnerGroup')}" icon="group_work" fixedMenuPosition>
Same explanation from above.

2021-05-28 08:41 UTC, lizable commented on src/components/backend-ai-session-launcher-new.ts
> +                              icon="storage" fixedMenuPosition>
Same explanation from above.

2021-06-03 02:35 UTC, adrysn requested changes
I just used the PR and unable to launch a session. Please refer to the following image.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7539358/120577233-fddcad80-c45e-11eb-97d7-ff1519cafe77.png">

The vertical align mismatch for the previous/next button and the arrows. And, how about using a bigger font size for the prev/next button?
<img width="423" alt="image" src="https://user-images.githubusercontent.com/7539358/120577373-35e3f080-c45f-11eb-994e-90d239905b88.png">

Personally, I think it would be good to have another button that states "LAUNCH NOW" in the middle of the prev and next buttons. When a user clicks this button, the session is launched with the default settings without visiting the next dialog contents. For example, when you launch an instance in AWS, you can see a button like "검토 및 시작"
<img width="584" alt="image" src="https://user-images.githubusercontent.com/7539358/120577725-ac80ee00-c45f-11eb-885d-8fca2b5a195d.png">

2021-06-14 05:25 UTC, inureyes commented
So many items with same id. It SHOULD BE UNIQUE. 

e.g. span id="launch-button-msg"

2021-06-14 05:54 UTC, lizable commented
> So many items with same id. It SHOULD BE UNIQUE.
> 
> e.g. span id="launch-button-msg"

I guess `launch-btn-msg` is only meaningful in `new-session-dialog`.
The rest of id declarations seems redundant to me. I'll remove those id declarations except in `new-session-dialog` right away.

2021-06-14 06:17 UTC, inureyes requested changes
* What if the set environment variable appears below?
* How about adding indicator below the Review and Start buttons to let users know what stage they are on.
* In the DOM, the ID must be single.

2021-07-02 09:11 UTC, inureyes approved these changes
LGTM

2021-07-02 09:11 UTC, merged