fix: load vfolders according to current project
lablup/backend.ai-webui pull request #1086
Opened 2021-07-27 16:02 UTC by lizable

related issue: #OP1431.

2021-07-28 01:52 UTC, inureyes requested changes
Please read review and rollback some codes.

2021-07-28 01:52 UTC, inureyes commented on src/components/backend-ai-storage-list.ts
> +        console.log(resp.msg);
@lizable  please delete / comment this.

2021-07-28 01:52 UTC, inureyes commented on src/components/backend-ai-webui.ts
> +    globalThis.backendaiclient.utils._writeRecentProjectGroup(this.current_group);
@lizable you SHOULD NOT CHANGE THIS PART since it is general SDK, not WebUI-only. global.backendaioptions only exists in WebUI.

2021-07-28 01:56 UTC, lizable commented on src/components/backend-ai-storage-list.ts
> +        console.log(resp.msg);
I'll delete it.

2021-08-10 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1086) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: lizable<br/>:x: Jihyun Kang<br/><hr/>**Jihyun Kang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai-webui?pullRequest=1086) it.</sub>

2021-08-17 14:15 UTC, adrysn requested changes
I feature is working well. However, I found the following compilation error. I don't think this is raised by this PR, but it needs to be fixed.

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/7539358/129742242-02a4030a-1975-4254-a770-c12c116eeccb.png">

2021-08-18 02:22 UTC, lizable commented
> I feature is working well. However, I found the following compilation error. I don't think this is raised by this PR, but it needs to be fixed.
> 
> <img alt="image" width="1527" src="https://user-images.githubusercontent.com/7539358/129742242-02a4030a-1975-4254-a770-c12c116eeccb.png">

It was found in `backend-ai-session-list` component, and It seems that It hasn't been used for a while, probably I just forgot to remove it when implementing #791.

2021-08-19 06:15 UTC, adrysn approved these changes
LGTM.

2021-08-19 13:37 UTC, merged