feat: refresh image list after rescanning
lablup/backend.ai-webui pull request #1090
Opened 2021-07-29 02:02 UTC by YejeeHa

#1065 
Add custom event `image-list-refreshed` where the rescanning image is done.

There is a problem when rescanning image in Maintenance page. 
- Click the 'rescan images' button and move to Environment page before rescanning is done ->  it seems refresh works well
- Wait until rescanning is done and go to Environment page -> only one item shows (screenshot below) and if I do something (e.g. check the checkbox, resize the column, etc.) the full list shows up.

<img width="1204" alt="스크린샷 2021-07-28 오후 6 49 45" src="https://user-images.githubusercontent.com/75378568/127419960-07f42fa8-2d4b-4252-bb15-99a38482ea31.png">

2021-07-29 07:43 UTC, lizable requested changes
The issue mentioned in the description of this PR, seems not happening in my environment, so far.
We need to inspect more about how it happens, under certain circumstances.
Except that, renaming the custom event is the only request change, for now.

2021-07-29 07:43 UTC, lizable commented on src/components/backend-ai-environment-list.ts
> +    document.addEventListener('image-list-refreshed', () => {
The event name `image-list-refreshed` seems that the image list has been changed, but inside of the event listener it's calling `_getImages()`, which requests the images from manager server.
In my opinion, we could change the name of custom event to have closer meaning of the event , such as `registry-rescanned`.

2021-07-29 07:43 UTC, lizable commented on src/components/backend-ai-maintenance-view.ts
> +                  icon="delete">
Great! 👍

2021-07-29 07:43 UTC, lizable commented on src/components/backend-ai-environment-list.ts
>            width: 70px;
Typo error catching, good! 👍

2022-05-04 16:34 UTC, inureyes approved these changes
LGTM

2022-07-20 02:43 UTC, merged