fix: refactor vfolder storage proxy components
lablup/backend.ai-webui pull request #1159
Opened 2021-11-23 08:16 UTC by lizable

2022-05-04 16:28 UTC, inureyes commented
@lizable Let's reduce confusion here.

 * For memory: byte to MB → 1048576 (actually it is MiB but is widely used MB for memory)
 * For storage: byte to MB → 1000000 (MiB)

I suggest to make both byteToMiB and byteToMB and apply to storage / memory view differently :).

2022-05-04 16:29 UTC, inureyes requested changes
@lizable Let's reduce confusion here.

* For memory: byte to MB → 1048576 (actually it is MiB but is widely used MB for memory)
* For storage: byte to MB → 1000000 (MiB)

I suggest to make both byteToMiB and byteToMB and apply to storage / memory view differently :).

2022-05-04 16:29 UTC, inureyes commented on resources/i18n/ko.json
> +    "FolderAlreadyExists": "폴더 명이 이미 존재합니다.",
폴더 명 → 폴더 이름.

2022-05-04 16:29 UTC, inureyes commented on src/components/backend-ai-agent-list.ts
> +    return Math.floor(value / 1000000);
IT should not be 1000000 but be 1048576.

2022-05-04 16:29 UTC, inureyes commented on src/components/backend-ai-session-list.ts
> +    return Math.floor(value / 1000000);
It should be 1048576.

2022-05-04 16:29 UTC, inureyes commented on src/components/backend-ai-session-view.ts
> +    return Math.floor(value / 1000000);
It should be 1048576.

2022-05-04 16:29 UTC, inureyes commented on src/components/backend-ai-credential-view.ts
> +  _gBToByte(value = 0) {
Reason to remove type annotation?

2024-05-08 07:22 UTC, closed without merging

2024-05-08 07:23 UTC, lizable commented
Closing this issue since it's been obsolete. We don't use piechart in storage-proxy component.