feat: add image name in session launcher
lablup/backend.ai-webui pull request #1195
Opened 2022-01-14 08:26 UTC by ggstone0523

Resolve:  lablup/backend.ai-webui #1074 

- display session information in last page of session launcher

**test image**
![PR1](https://user-images.githubusercontent.com/43121372/149474120-95981b1d-070a-44d7-8553-f0cf3662588d.png)

2022-01-14 08:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai-webui?pullRequest=1195) it.</sub>

2022-01-14 09:32 UTC, lizable requested changes
The layout seems fine, but why don't we enhance it more according to the comments below?

2022-01-14 09:32 UTC, lizable commented on src/components/backend-ai-session-launcher.ts
>            <div id="progress-04" class="progress center layout fade">
Let's add the type of session (`BATCH` or `INTERACTIVE`).
And I cannot see proper session info when I enabled two keys `debug` or `allowManualImageNameForSession` to true in configuration file(`config.toml`). Please update when the user uses the manual image.

**Screenshot**:
<img width="432" alt="using-manual-image-in-session-launcher-01" src="https://user-images.githubusercontent.com/46954439/149491911-fac9ec87-631a-41a8-a68f-d6cbd1bde4af.png">
<img width="432" alt="using-manual-image-in-session-launcher-02" src="https://user-images.githubusercontent.com/46954439/149491924-fcea7841-bf99-4fc9-a51b-67c3058b89be.png">

As you can see the pictures above, there's no image description and the environment doesn't match with logo.

2022-01-17 08:03 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

**1. add type of session**

**Interactive**
![PR1_review1_1](https://user-images.githubusercontent.com/43121372/149725637-b95ffaad-6a14-4b5d-99b8-63d8b0065ea5.png)

**Batch**
![PR1_review1_2](https://user-images.githubusercontent.com/43121372/149725687-0e9d6cbd-a51f-4675-8bcb-7dac4932ffb5.png)


**2. display session information for manual image**

![PR1_review1_3](https://user-images.githubusercontent.com/43121372/149725716-d58afa90-ffa1-4f18-ac01-2081d44d38bb.png)

2022-01-17 08:49 UTC, lizable requested changes
I would like to suggest two things:
First, Let's display session type below environment.
Although session type is important enough, but environment is much more important than the type.
And Also, How about making own property (Object) for image?
For now there are many duplicated string processing methods such as `value.split(':').pop()?.split('-')...`
Unless the purpose of the duplicated statement is for readability, converting to property and add general processing function would be better, I think.

2022-01-18 02:46 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

**1. Display session type below environment**
![PR1_review2_1](https://user-images.githubusercontent.com/43121372/149861794-56dffd1f-772c-4136-8940-90af1e067cbf.png)

**2.  Change duplicated string processing methods to function**
- Change duplicated string processing methods for 'manualImageName' to '_preProcessingManualImageInfo' function.
- '_preProcessingManualImageInfo' function takes derive kernel infomation from manualImageName and save it in manualImageInfo.

2022-01-18 09:10 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

**1. Display session type below session environment**
![PR1_review3_1](https://user-images.githubusercontent.com/43121372/149903811-53f1b384-5c61-46a4-9801-932d42e0d50f.png)

**2. Change repeated element to object**
- Change repeated element in 'sessionInfo' to 'sessionInfoObj' object
- '_preProcessingSessionInfo' function takes derive kernel infomation from manualImageName or selector and save it in 'sessionInfoObj'.
- '_processingSessionEnvironment' function is processing session environment value.
- '_processingSessionVersion' function is processing session version value.

2022-01-18 09:17 UTC, Sujin-Kim1 requested changes

2022-01-18 09:17 UTC, Sujin-Kim1 commented on src/components/backend-ai-session-launcher.ts
> +    'isSelectorTrue': false,
How about renaming this variable to `isVersionSelected`?

2022-01-18 09:17 UTC, Sujin-Kim1 commented on src/components/backend-ai-session-launcher.ts
> +    'isManualTrue': false
I think `isManualImageName` would be more comprehensive.

2022-01-18 09:17 UTC, Sujin-Kim1 commented on src/components/backend-ai-session-launcher.ts
> +    }
This code is same with `this.sessionInfoObj.isManualTrue = this.manualImageName?.value ? true : false`. But it's okay now, so you can go in a better direction as you think.

2022-01-18 10:48 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

**1. Change sessionInfoObj attribute name**
- change 'isSelectorTrue' to 'isVersionSelected'
- change 'isManualTrue' to 'isManualImageName'

**2. Change _preProcessingSessionInfo function logic**
- change if statement to assignment statement

2022-01-20 11:16 UTC, ggstone0523 commented
### The revision was completed.

**1. display icon in session info for non installed manual image**
**2. Separate Constraint infomation from Base information**

2022-01-24 02:18 UTC, lizable approved these changes
LGTM.

2022-01-24 02:20 UTC, Sujin-Kim1 approved these changes
LGTM

2022-01-27 08:58 UTC, inureyes approved these changes
LGTM.

2022-01-27 08:58 UTC, merged