fix: change auto_logout value set logic
lablup/backend.ai-webui pull request #1200
Opened 2022-01-20 07:17 UTC by ggstone0523

### Resolve: lablup/backend.ai-webui #1173 

**1. bugfix for auto logout feature**

- This bug is caused by changing the 'auto logout' setting on the 'UserSettings' page does not change value of 'this.auto_logout' accordingly.
- The reason why the value of 'this.auto_logout' does not change is that it continues to receive the value only from element 'autoLogout' of config.toml.

2022-01-24 13:02 UTC, lizable commented on src/components/backend-ai-webui.ts
>      }
It works okay, but It seems too long to use ternary operation. How about using plain if-else statement for better readability?

2022-01-24 13:04 UTC, lizable requested changes
I'm not sure it's okay to use ternary operation in such a long statement. @ggstone0523
But All seems to work fine, so I want your opinion on this code.

2022-01-24 13:40 UTC, lizable commented
LGTM!

2022-01-24 13:40 UTC, ggstone0523 commented
I also think so writing an if-else statement is a better way in terms of readability than using a ternary operation.

2022-01-28 01:32 UTC, Sujin-Kim1 approved these changes
LGTM

2022-01-28 07:51 UTC, lizable approved these changes

2022-02-16 03:34 UTC, inureyes commented
LGTM

2022-02-16 03:34 UTC, merged