fix: add scroll to session list tab in session tab
lablup/backend.ai-webui pull request #1201
Opened 2022-01-21 09:40 UTC by ggstone0523

Resolve: lablup/backend.ai-webui #1198

- This bug is caused by inner block in 'session tab' h3 block is overflowed when window size is narrow.
- Add scroll to session list tab in session tab to prevent overflow

**test image**
![PR3](https://user-images.githubusercontent.com/43121372/150502376-33849481-25c2-45a3-87fc-3c67b1349cc5.png)

2022-01-21 13:21 UTC, Sujin-Kim1 requested changes

2022-01-21 13:21 UTC, Sujin-Kim1 commented on src/components/backend-ai-session-view.ts
> +            <div class="scroll hide_scrollbar">
We use kebab-case in class. Please rename `hide_scrollbar` to `hide-scrollbar`.

2022-01-21 13:30 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

1. change 'hide_scrollbar' to 'hide-scrollbar'

2022-01-21 13:43 UTC, Sujin-Kim1 approved these changes
LGTM.

2022-01-28 07:58 UTC, lizable commented on src/components/backend-ai-session-view.ts
>              </div>
@ggstone0523 Let's remove `isSupportingFab` attribute in Line 475. It seems like a legacy code and we are no longer using that attribute anymore.

2022-01-28 08:00 UTC, lizable approved these changes
I removed `isSupportingFab` attribute since we don't use it anymore.
Except that, it works fine.

2022-01-28 08:27 UTC, ggstone0523 commented
@lizable thanks!

2022-02-16 04:07 UTC, inureyes approved these changes
LGTM

2022-02-16 04:07 UTC, merged