send target app's protocol (http or tcp) when starting wsproxy
lablup/backend.ai-webui pull request #1211
Opened 2022-01-27 06:14 UTC by kyujin-cho

This PR adds new protocol variable which defines app's underlying transportation protocol. Sending protocol to wsproxy will help wsproxy determine equivalent proxying mechanism.

2022-01-27 09:01 UTC, inureyes reviewed
Do we need to update proxy in the web UI (`src/lib/wsproxy`) ? I think it does not need to accept the protocol since it just uses localhost HTTP, however for the equivalent API interface between web version and local one?

2022-01-27 09:01 UTC, inureyes commented on src/components/backend-ai-app-launcher.ts
> +    console.log(kInfo.compute_session.service_ports)
Please remove the debug lines. :D

2022-01-27 10:04 UTC, kyujin-cho commented
> Do we need to update proxy in the web UI (`src/lib/wsproxy`) ? I think it does not need to accept the protocol since it just uses localhost HTTP, however for the equivalent API interface between web version and local one?

as you mentioned, we can just skip handling `protocol` query parameter on the webUI's wsproxy since we can't handle TCP based proxying on web version. But perhaps we can normalize `manager.js`' TCP app blocking code block with this `protocol` parameter. I'll add a new commit about this feature.

2022-05-03 05:06 UTC, inureyes commented
@kyujin-cho  It does not work since application call returns 404.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/949915/166406784-bfc90173-a5e4-4c93-bacb-78169f1a4430.png">

2022-05-03 05:07 UTC, inureyes requested changes
It is not working as intended. Needs some polishings.

2022-09-13 07:04 UTC, inureyes approved these changes
LGTM

2022-09-13 07:04 UTC, merged