fix: show login dialog when cluster dialog disappear
lablup/backend.ai-webui pull request #1219
Opened 2022-02-03 05:15 UTC by ggstone0523

Resolve: lablup/backend.ai-webui #1168 

- This bug caused by auto closing backend-ai-dialog when press esc button
- Add event handler to cluster dialog
- Event handler show login dialog when press esc button

**test image**
1. go to login page
![PR5_review0_1](https://user-images.githubusercontent.com/43121372/152285231-8b25286d-7ba6-440f-8226-e6801a46889f.png)

2. press esc button
![PR5_review0_2](https://user-images.githubusercontent.com/43121372/152285243-c924b356-1bf5-4c98-aa99-0779dafe0ca7.png)

3. press esc button once again
![PR5_review0_3](https://user-images.githubusercontent.com/43121372/152285262-239f49f5-5176-4877-b2e2-197ecd864756.png)

2022-02-18 07:14 UTC, ggstone0523 commented
### The revision was completed.

1.  show login dialog when press X button

2022-02-18 08:13 UTC, Sujin-Kim1 commented
I think `escapeAction` is not necessary because it works well without that. 
It's trivial, but from the second time, if you press esc to make the login dialog disappear, the blank page will appear again.

2022-02-19 10:48 UTC, ggstone0523 commented
In my development environment(safari, chrome),  cluster dialog disappear when press esc key if remove `escapeKeyAction`.
and, i avoid closing the login dialog with the esc key when the login dialog appears second time or press esc key late (because if press esc key late, cluster dialog did not appear)

2022-02-21 05:38 UTC, ggstone0523 commented
### The revision was completed.

1. prevent login dialog closed by esc key pressing
2. add 'preventEscKeyClose' attribute to backend-ai-dialog

2022-02-21 06:01 UTC, Sujin-Kim1 approved these changes
LGTM.

2022-02-21 08:08 UTC, lizable requested changes
I'm not sure about whether we should need boolean property instead of using the internal value that mwc-dialog supports.
IMHO, using escapeKeyAction is better since we don't need to assign an extra function for value checking.
What do you think of this approach @ggstone0523 @Sujin-Kim1 ?

2022-02-21 08:08 UTC, lizable commented on src/components/backend-ai-dialog.ts
Why don't we just use string value (`close`) as default value which is the same way the `mwc-dialog` supports?

2022-02-21 08:23 UTC, ggstone0523 commented
I think is good!

2022-02-21 08:34 UTC, ggstone0523 commented
### The revision was completed by reflecting the comments.

- remove preventEscapeKeyClose attribute and append escapeKeyAction attribute in backend-ai-dialog

2022-02-21 09:39 UTC, ggstone0523 commented
The revision was completed

- remove cluster dialog protection from disappear

2022-02-21 10:20 UTC, ggstone0523 commented
### The revision was completed.

- add 'escapeKeyAction' attribute to block-panel

2022-02-21 10:24 UTC, lizable approved these changes
LGTM.

2022-02-21 10:26 UTC, merged