fix: activate superadmin's all vfolder listing feature
lablup/backend.ai-webui pull request #1237
Opened 2022-02-20 18:35 UTC by SonMinWoo

resolve: https://github.com/lablup/backend.ai/issues/321

2022-02-22 01:55 UTC, lizable requested changes
I have a few things to request. Please refer to the comments below.

2022-02-22 01:55 UTC, lizable commented on src/components/backend-ai-resource-broker.ts
> +   async updateVirtualFolderList(userEmail = false) {
The type of default value of parameter `userEmail` doesn't seem to have a match with SDK function in [here](https://github.com/lablup/backend.ai-webui/pull/1237/files#diff-6ab6a3b84b5af19510d01f3a5c155018416e21b94b7090c2a4a22e0a1d68e33bR1421-R1429).
It's string, not boolean.

2022-02-22 01:55 UTC, lizable commented on src/components/backend-ai-session-launcher.ts
> +      await this.resourceBroker.updateVirtualFolderList(userEmail).then(() => {
Any reason for using `await` keyword and `.then()` keyword at the same time?

2022-02-22 01:55 UTC, lizable commented on src/components/backend-ai-session-launcher.ts
> +                  <mwc-icon-button icon="refresh" class="blue"
If I input any user account(email) and rewrite it, it doesn't update according to the new input.

2022-02-22 01:55 UTC, lizable commented on src/lib/backend.ai-client-node.ts
> +    if (groupId || userEmail) {
I think it's better to use condition statements separately.

2022-02-23 01:49 UTC, lizable approved these changes
LGTM

2022-04-11 16:07 UTC, lizable commented
I just updated two things during delegate session creation:
- [x] Enable the session delegation checkbox only if the owner's keypair is valid.
- [x] Fetch the owner's accessible vfolder list only if the owner's keypair is valid.

2022-04-12 13:40 UTC, inureyes commented
@lizable Great!

2022-04-12 13:41 UTC, inureyes approved these changes

2022-04-12 13:41 UTC, merged