Failing to update a compute session's name will set the value of edit element to `undefined`
lablup/backend.ai-webui pull request #1264
Opened 2022-04-05 07:35 UTC by Sujin-Kim1

this resolve #1260

2022-04-06 12:08 UTC, adrysn requested changes
Overall, this PR improves the interaction with the rename field. However, I find that the validation checker sometimes displays inappropriate messages. Example images below:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/7539358/161970349-879de9fa-3373-493b-a016-bc24e1824cbb.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/7539358/161970455-f39480dd-d1d0-4678-8ebf-e01b46b02980.png">
<img width="237" alt="image" src="https://user-images.githubusercontent.com/7539358/161970531-c9071c93-bcb4-428e-b5e4-4a30968969b5.png">

If it is hard to display in every situation, I think just displaying `slugged strings (>3 chars)` might be an alternative option.

2022-04-11 17:03 UTC, lizable commented on resources/i18n/ko.json
> +      "SluggedStrings": "고유문자열로 입력해주세요 (3 > 글자 수)",
How about just translating the number of minimum characters to 최소 4자 이상 instead of (3 > 글자수)?

2022-04-11 17:05 UTC, lizable requested changes
It works fine. 
But IMHO, It would be nicer if there's a bit of touch-up on translation.
Please check out the review below.

2022-04-11 17:11 UTC, Sujin-Kim1 commented on resources/i18n/ko.json
> +      "SluggedStrings": "고유문자열로 입력해주세요 (3 > 글자 수)",
That's great. I fixed it right away.

2022-04-11 17:16 UTC, lizable approved these changes
LGTM.

2022-04-12 13:42 UTC, merged

2022-04-12 13:42 UTC, inureyes reviewed
LGTM