Support to select folder hosts for import Github/Gitlab repo
lablup/backend.ai-webui pull request #1279
Opened 2022-04-21 08:41 UTC by studioego

Support to select folder hosts for import Github/Gitlab repository.

If you import Github/Gitlab repository, It only saves default host storage.
However, one of Some customers needs to select some storage
not only default host storage but one of custom host storage.

As a result, We support to select folder hosts for import Github/Gitlab repositories.

related #1278

2022-04-22 16:22 UTC, adrysn requested changes
I think the layout should be more aligned... 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/7539358/164752058-6dd49be6-6129-407f-aef5-f970ca27d715.png">

Alternatively, I suggest the following:
* Hide the Host from the main page.
* When a user clicks the "GET TO FOLDER" button, display the Host panel as a dialog.
  * For convenience, just use the host without opening the Host dialog when there is only one host.

In the meantime, what is the purpose of the information button? It just displays "No description" message.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/7539358/164756485-fa7f7880-6983-4ea5-a02e-c1c1bdc517ae.png">

2022-04-25 06:05 UTC, studioego commented
> I think the layout should be more aligned...

I think your alternative option, I decide the first more aligned layout option.

> In the meantime, what is the purpose of the information button? It just displays "No description" message.
That feature copy from 'Data & Storage new storage popup.
<img width="808" alt="image" src="https://user-images.githubusercontent.com/20002/165029684-9ea99e80-eb7e-453a-bbcd-33d8ba113186.png">
If you don't want to shows information button, I'll remove information button.

2022-04-25 07:26 UTC, studioego commented
Now, I changed the import screen layout. 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/20002/165039439-61a3bdd8-0bda-44bf-affa-38b341a8813f.png">
However, Unlike Import Gitlab repository layout, To set Github repository layout 
is difficult for me.
I will think about a better layout.

2022-04-25 08:07 UTC, studioego commented
Fix layout!
Below is fixed import layout. 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/20002/165046775-089811fd-2c40-4d00-bcc4-c8d7eca80c59.png">

2022-04-25 08:35 UTC, studioego reviewed
Following your opinion, I changed both Github and Gitlab layouts.
However, Your alternative option should be considered. 
(I have to learn more typescript and modern html, etc)

2022-04-25 15:50 UTC, adrysn requested changes
The updated layout looks as you intended in the Korean page but not in the English page. We need to think about a way to align those elements in any languages.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7539358/165125731-e0f36836-19a3-4e37-b665-33cd6e7716de.png">

2022-04-26 03:09 UTC, studioego commented
> The updated layout looks as you intended in the Korean page but not in the English page. We need to think about a way to align those elements in any languages.
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/7539358/165125731-e0f36836-19a3-4e37-b665-33cd6e7716de.png">

I got it. I'll try to resolve the layout issue.

2022-04-26 06:50 UTC, studioego commented
I checked the import layout on i18n environment ( sucn as English, Bahasa Indonesia, etc)

* English 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/20002/165238997-028f9669-f9c7-4f3e-b488-96c069d9f1b6.png">

* Korean
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20002/165239084-145bd68b-65e7-47d4-8c20-4c5cd4bfdf11.png">


* Bahasa Indonesia
<img width="764" alt="image" src="https://user-images.githubusercontent.com/20002/165238562-eedaebf9-3657-41b3-8bb7-3331a51a409e.png">

* Mongolian
<img width="754" alt="image" src="https://user-images.githubusercontent.com/20002/165238599-28fb3edf-011e-4e25-a38d-bd910ef9e717.png">


* Russian

<img width="776" alt="image" src="https://user-images.githubusercontent.com/20002/165238480-29cc6889-3dd9-4c22-95a0-40aa821e3642.png">

* French
<img width="757" alt="image" src="https://user-images.githubusercontent.com/20002/165238891-01ffb191-8373-49e6-b597-15fda8a0b906.png">

2022-04-27 04:54 UTC, adrysn requested changes
The features are working fine for me. I found minor issues in styles and not-used code blocks, and if they are fixed, I think I can merge this PR.

2022-04-27 04:54 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +import {unsafeHTML} from 'lit/directives/unsafe-html.js';
I don't see any usage of the `unsafeHTML` in this PR. If it is not used,please remove it.

2022-04-27 04:54 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +        }
Let's merge these blocks into:
```javascript
mwc-textfield#github-repo-url,
mwc-textfield#gitlab-repo-url {
  width: 100%;
}
```

Or, just tag the same class, such as `repo-url`, to both of the elements and:
```javascript
mwc-textfield.repo-url {
  ...
} 
```

2022-04-27 04:54 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +        }
Let's merge these blocks into:
```javascript
mwc-textfield#github-repo-url,
mwc-textfield#gitlab-repo-url {
  width: 100%;
}
```

Or, just tag the same class, such as `repo-url`, to both of the elements and:
```javascript
mwc-textfield.repo-url {
  ...
} 
```

2022-04-27 04:54 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +  }
If not use, please remove it.

2022-04-27 04:54 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +  }
If not use, please remove it.

2022-04-27 13:10 UTC, studioego reviewed
Applyed

2022-04-27 13:10 UTC, studioego commented on src/components/backend-ai-import-view.ts
> +  }
delete it

2022-04-27 13:10 UTC, studioego commented on src/components/backend-ai-import-view.ts
> +import {unsafeHTML} from 'lit/directives/unsafe-html.js';
delete it

2022-04-27 13:10 UTC, studioego commented on src/components/backend-ai-import-view.ts
> +        }
change the `repo-url` tags

2022-04-27 16:24 UTC, adrysn approved these changes
LGTM.

2022-04-27 16:24 UTC, adrysn commented on src/components/backend-ai-import-view.ts
> +import {unsafeHTML} from 'lit/directives/unsafe-html.js';
I don't see any usage of the `unsafeHTML` in this PR. If it is not used,please remove it.

2022-04-27 16:25 UTC, merged