Feature: Session lifetime config in resource policy
lablup/backend.ai-webui pull request #1304
Opened 2022-05-09 09:16 UTC by lizable

## Description
This PR resolves a new configuration `max_session_lifetime`, which can be applied in resource policy.
Related: [manager#583](https://github.com/lablup/backend.ai-manager/pull/583)
> ⚠️ NOTE: 
> - Value "0" in `max_session_lifetime` means Infinite(♾) likewise in `idle_timeout`.
> - This feature are available from `22.03`.

## Before
- Create Resource Policy Dialog
<img width="516" alt="Create-Resource-Policy-before" src="https://user-images.githubusercontent.com/46954439/167379359-9ae908ff-894f-49f9-85e6-a1b5f7ed9ee6.png">

- Update Resource Policy Dialog
<img width="516" alt="Update-Resource-Policy-before" src="https://user-images.githubusercontent.com/46954439/167379375-6727be24-8280-42e3-a348-93aa468b1035.png">

## After
- Create Resource Policy Dialog
<img width="516" alt="Create-Resource-Policy" src="https://user-images.githubusercontent.com/46954439/167379069-5f167211-b6ad-444d-8b49-5e776d2c7e5c.png">

- Update Resource Policy Dialog
<img width="516" alt="Update-Resource-Policy" src="https://user-images.githubusercontent.com/46954439/167379103-bc604d3b-45b4-4807-beba-f35b716f12ce.png">

2022-05-09 14:11 UTC, adrysn requested changes
Minor code style issues.

2022-05-09 14:11 UTC, adrysn commented on src/components/backend-ai-session-launcher.ts
> +  }}"
This worsens the readability.

2022-05-09 15:20 UTC, lizable commented on src/components/backend-ai-session-launcher.ts
> +  }}"
hmm, I guess it's because of "eslint" code styling. I'll revert to the previous code style.

2022-05-09 15:33 UTC, adrysn commented on src/components/backend-ai-session-launcher.ts
> +  }}"
Perhaps, we need to update the eslint config not to rearrange the code in a weird way.

2022-05-09 15:35 UTC, adrysn requested changes
Further minor styling issues. We may need to change the eslint config.

2022-05-09 15:35 UTC, adrysn commented on src/components/backend-ai-session-launcher.ts
> +  }}"
Here as well.

2022-05-09 15:35 UTC, adrysn commented on src/components/backend-ai-session-launcher.ts
> +  }}"
Here as well.

2022-05-10 00:56 UTC, adrysn approved these changes
LGTM.

2022-05-10 00:57 UTC, merged