fix: change the size of the popup to fit the text
lablup/backend.ai-webui pull request #1383
Opened 2022-07-19 11:24 UTC by dan-2ee

## Fix
I just increased the length of the dialog to prevent scrolling in the text.

## Change
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr>
<tr>
<td>![before](https://user-images.githubusercontent.com/65989401/179738700-bd97f900-1bf2-475b-a517-34c06a6bccb1.jpg)</td>
<td><img width="245" alt="after" src="https://user-images.githubusercontent.com/65989401/179738827-5227bcfe-4f21-4c13-b9d5-805cf1072bff.png"></td>
</tr>
</table>
resolve: #1349

2022-07-19 15:40 UTC, Jaewoook commented
If the message is longer than two lines, the same scrolling issue could appear again. I suggest that adaptive component height is better than this.

2022-07-19 18:12 UTC, lizable requested changes
I confirmed that if the description in indicator exceeds two lines, then it also creates a scrollbar, [which has been issued](https://github.com/lablup/backend.ai-webui/pull/1383#issuecomment-1189212613) by @Jaewoook.
Instead of using a hardcoded value, let's use `auto`.

2022-07-19 18:13 UTC, lizable commented
@dan-2ee And please check whether it works properly in cross-browsers.

2022-07-20 01:00 UTC, lizable commented
And once more, it's not necessary, but I think it's better to "auto-resize" the font size to avoid line breaks if there are one or two characters exceeding the total width of snackbar.

2022-07-20 05:26 UTC, dan-2ee commented
I think it's better to set the height automatically rather than hard.

2022-07-20 06:33 UTC, dan-2ee commented
> And I have one more thing to suggest. it's not necessary, but I think it's better to "auto-resize" the font size to avoid line breaks if there are one or two characters exceeding the total width of snackbar. How does this sound to you? @dan-2ee

It's good to adjust the letter size automatically, but I think it's also a way to prevent words from being separated by letters. So I added the "word-break" property to prevent words from being separated from unacceptable positions.
Please review it.

2022-07-20 07:09 UTC, lizable approved these changes
LGTM.

2022-07-20 07:09 UTC, merged

2022-07-20 15:00 UTC, dan-2ee commented
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr>

<tr>
<td><img width="245" alt="after" src="https://user-images.githubusercontent.com/65989401/179739359-f7defffc-0a6a-44ce-8e50-9e3aebce91e5.jpg"></td>
<td><img width="245" alt="after" src="https://user-images.githubusercontent.com/65989401/180015154-446a965a-ee5f-4053-b3b6-57c2071980f2.jpg"></td>
</tr>

</table>