fix: Manual image name is not required in Session launcher
lablup/backend.ai-webui pull request #1397
Opened 2022-07-27 08:26 UTC by dan-2ee

## Fix
* An error occurred because manualImageName.value is used as kernalname even though manualimagename field is empty in debug mode.
So I modified the manual image name field to be used as a kernal name only when it is not empty.
* In Session launcher, manual image name is not required but optional (in debug mode or when allowManualImageNameForSession is true)

resolve #1365

2022-07-27 10:51 UTC, Jaewoook requested changes
The *manual image name* field appears only in debug mode. So I think just check that is truthy value using AND operator is more clear rather than this OR operator.

2022-07-27 10:58 UTC, Jaewoook commented
And of course, I think 

> The _manual image name_ field appears only in debug mode. So I think just check that is truthy value using AND operator is more clear rather than this OR operator.

@dan-2ee I'm verry sorry, I was wrong. Manual image name input without debug mode is also supported.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/5039744/181230879-a82cd1e8-7212-4c25-8875-807c4aac5346.png">

2022-07-27 10:58 UTC, Jaewoook approved these changes

2022-08-02 02:51 UTC, lizable approved these changes
LGTM.

2022-08-02 02:51 UTC, merged