fix/add endpoint validation
lablup/backend.ai-webui pull request #1470
Opened 2022-09-11 14:38 UTC by jangjichang

related issue: https://github.com/lablup/backend.ai-webui/issues/1468

before
User has entered a invalid endpoint format
![image](https://user-images.githubusercontent.com/29423339/189533521-a508d87d-7c87-425c-8c5f-a5b10713b153.png)

after
![image](https://user-images.githubusercontent.com/29423339/189533533-6aea730a-ce23-486e-aa93-0a2cd217c0a8.png)

2022-09-13 01:02 UTC, Sujin-Kim1 requested changes

2022-09-13 01:02 UTC, Sujin-Kim1 commented on src/components/backend-ai-login.ts
> +        if (!this.api_endpoint.toLowerCase().startsWith('http://') && !this.api_endpoint.toLowerCase().startsWith('https://')) {
How about using `validityTransform`?
ref: https://github.com/lablup/backend.ai-webui/blob/main/src/components/backend-ai-signup.ts#L340

2022-09-13 01:02 UTC, Sujin-Kim1 commented on resources/i18n/en.json
> +    "APIEndpointStartWith": "API Endpoint must start with http:// or https://.",
Please use i18n.
1. Run `make i18n`
2. Translate other words if you can.

More details: https://github.com/lablup/backend.ai-webui#extracting-i18n-resources

2022-09-13 01:04 UTC, inureyes requested changes
Please review the comments and let's upgrade input form to use validityTransform :)

2022-09-13 01:04 UTC, inureyes commented on src/components/backend-ai-login.ts
> +        if (!this.api_endpoint.toLowerCase().startsWith('http://') && !this.api_endpoint.toLowerCase().startsWith('https://')) {
I agree with Sujin :D

2023-03-20 14:09 UTC, inureyes commented on src/components/backend-ai-login.ts
> +        if (!this.api_endpoint.toLowerCase().startsWith('http://') && !this.api_endpoint.toLowerCase().startsWith('https://')) {
@Sujin-Kim1 Let's finish this PR. It is from contributor's repo, therefore there is no way to update the repo. It will be better to branch and make a new PR with reference to this PR.

2023-03-20 14:12 UTC, agatha197 commented on src/components/backend-ai-login.ts
> +        if (!this.api_endpoint.toLowerCase().startsWith('http://') && !this.api_endpoint.toLowerCase().startsWith('https://')) {
okay, I'll do that.

2023-03-26 03:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai-webui?pullRequest=1470) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai-webui?pullRequest=1470) it.</sub>

2023-04-17 06:17 UTC, Sujin-Kim1 commented
this PR will be handled by https://github.com/lablup/backend.ai-webui/pull/1689.
close this issue.

2023-04-17 06:17 UTC, closed without merging