add: new environment image tag parsing aliases
lablup/backend.ai-webui pull request #1535
Opened 2023-01-03 01:15 UTC by inureyes

This PR resolves #1531

2023-01-03 06:46 UTC, Sujin-Kim1 requested changes
Thanks to handle it! It still looks good now, but can I modify it to automatically convert by pattern? (For example, to convert from tf2.* to TensorFlow 2.*)

2023-01-03 06:46 UTC, Sujin-Kim1 commented on src/components/backend-ai-resource-broker.ts
> +        console.log(this.imageTagAlias);
Please remove this line :)

2023-01-03 11:02 UTC, inureyes commented
> Thanks to handle it! It still looks good now, but can I modify it to automatically convert by pattern? (For example, to convert from tf2.* to TensorFlow 2.*)

It will be better for specific patterns such as tf2.*, pytorch1.*, pytorch2.* and cuda*.*

2023-01-12 05:04 UTC, Sujin-Kim1 commented
> > Thanks to handle it! It still looks good now, but can I modify it to automatically convert by pattern? (For example, to convert from tf2.* to TensorFlow 2.*)
> 
> It will be better for specific patterns such as tf2._, pytorch1._, pytorch2.* and cuda*.*

I added some codes that replace the tags that have specific patterns.

2023-01-20 15:19 UTC, adrysn approved these changes
LGTM.

2023-01-20 15:23 UTC, merged