Bugfix: set max values of session slider based on `keypair_limits` and `hideAgents` setting when `alwaysEnqueueComputeSession` is true
lablup/backend.ai-webui pull request #1608
Opened 2023-02-24 09:21 UTC by Sujin-Kim1

fixes https://github.com/lablup/giftbox/issues/195

`this.total_slot` is calculated by considering both `keypair_resource_limit`(keypair_limits) and `total_resource_group_slot` as shown below. Use this value to calculate the slider maximum when enqueue session is possible.

🚨 FYI,`this.total_slot` value will vary if other users within the same Resource Group create sessions.

```typescript
if (keypair_resource_limit['cpu'] === 'Infinity') { // When resource is infinity, use scaling group limit instead.
  total_slot['cpu'] = total_resource_group_slot['cpu'];
} else {
  total_slot['cpu'] = keypair_resource_limit['cpu'];
}
```
+) fix: avoid getting property from undefined.

2023-02-24 09:25 UTC, lizable requested changes
@agatha197   It's more complicated than we expected. I'll handle this issue from now on.

2023-02-26 00:45 UTC, adrysn requested changes
For me, this is not working. I confirmed that the `hideAgent` and `alwaysEnqueueComputeSession` are set to `true`.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/7539358/221386207-bdf908b8-5cef-4092-9031-30ac0ed2e545.png">

I have three resource presets:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/7539358/221386088-4b3e66dd-15b2-49d4-8c21-6ae9aeeeea16.png">

I set the user's resource policy to 4 cores, 8 GB memory, and 0.5 fGPU.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/7539358/221386158-69a479b0-9041-48c9-a929-b25ac63da5ea.png">

So, at least the resource preset `GPU-Suppor` should appear in the list. But, nothing is displayed in the user's session launcher. Also, GPU slider is disabled.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/7539358/221386035-ad9d9925-128c-4f91-83b7-14d61478d8bb.png">

When I change the resource policy of the user with unlimited values:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7539358/221386272-f72e4039-0ce5-4f22-86c9-91993370c2d7.png">

I see two resource presets (I don't know why `GPU-Full` is not displayed):
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7539358/221386286-5c763d71-2eee-4304-adf4-5e13c561f9e9.png">

2023-02-26 03:01 UTC, lizable commented
> For me, this is not working. I confirmed that the `hideAgent` and `alwaysEnqueueComputeSession` are set to `true`. <img alt="image" width="311" src="https://user-images.githubusercontent.com/7539358/221386207-bdf908b8-5cef-4092-9031-30ac0ed2e545.png">
> 
> I have three resource presets: <img alt="image" width="500" src="https://user-images.githubusercontent.com/7539358/221386088-4b3e66dd-15b2-49d4-8c21-6ae9aeeeea16.png">
> 
> I set the user's resource policy to 4 cores, 8 GB memory, and 0.5 fGPU. <img alt="image" width="506" src="https://user-images.githubusercontent.com/7539358/221386158-69a479b0-9041-48c9-a929-b25ac63da5ea.png">
> 
> So, at least the resource preset `GPU-Suppor` should appear in the list. But, nothing is displayed in the user's session launcher. Also, GPU slider is disabled.
> 
> <img alt="image" width="428" src="https://user-images.githubusercontent.com/7539358/221386035-ad9d9925-128c-4f91-83b7-14d61478d8bb.png">
> 
> When I change the resource policy of the user with unlimited values: <img alt="image" width="507" src="https://user-images.githubusercontent.com/7539358/221386272-f72e4039-0ce5-4f22-86c9-91993370c2d7.png">
> 
> I see two resource presets (I don't know why `GPU-Full` is not displayed): <img alt="image" width="623" src="https://user-images.githubusercontent.com/7539358/221386286-5c763d71-2eee-4304-adf4-5e13c561f9e9.png">

@adrysn Did you set the image doesn't require GPU resource such as Python 3.9? If you did, then GPU resource slider would be disabled. If not, I need to dig down little more.

2023-02-26 03:28 UTC, adrysn commented
I used `ngc-pytorch:22.12`. Every resource presets are visible at first, but after other users allocate resources, it dissapeared.

2023-03-06 10:41 UTC, lizable commented
## Updates
- When both `always_enqueue_session` and `hideAgents` key in the configuration are enabled, then users' max resource limit follows `max_***_per_container keys` in the configuration file.
-  When `always_enqueue_session` is enabled but `hideAgents` is set to `false`, then the users' max resource limit follows the total amount of resources that the current(selected) resource group contains.

@Sujin-Kim1 @adrysn Could you review this PR?

2023-03-07 10:26 UTC, agatha197 commented on src/components/backend-ai-session-launcher.ts
>            const image_mem_max = globalThis.backendaiclient.utils.changeBinaryUnit(mem_metric.max, 'g', 'g');
LGTM. But just remove this line, please. I got this warning message.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/28584164/223347609-67adc843-bd5d-4083-a086-f5c40becd05e.png">

2023-03-08 04:26 UTC, lizable commented on src/components/backend-ai-session-launcher.ts
>            const image_mem_max = globalThis.backendaiclient.utils.changeBinaryUnit(mem_metric.max, 'g', 'g');
Confirmed. I just removed Line 1931 since there's a statement that uses `mem_metric.max`.

2023-03-08 04:29 UTC, lizable approved these changes

2023-03-14 08:06 UTC, lizable commented
@adrysn Could you review this issue this week?

2023-04-17 06:25 UTC, inureyes commented
Please resolve the conflict. @Sujin-Kim1

2023-12-16 05:07 UTC, adrysn commented
Is this PR stilll mergable? If the NEO launcher will be introduced soon, it might be better to close this and deal this issue in the new launcher.

2024-09-02 13:10 UTC, closed without merging

2024-09-02 13:11 UTC, yomybaby reviewed
This PR is no longer valid, so we will close it. The `alwaysEnqueueComputeSession` has been deprecated, and the changes in this PR have already been implemented in the NEO Session Launcher.