fix: set request timeout to infinity when pulling a image
lablup/backend.ai-webui pull request #1672
Opened 2023-03-31 06:25 UTC by Sujin-Kim1

resolves https://github.com/lablup/giftbox/issues/196

Web UI's image download feature always returns 504 error since the session stays in PULLING status for more than request timeout.

2023-03-31 06:29 UTC, lizable commented
We really need SSE on receiving the progress (to measure how much time is left...) but let's set the timeout to infinity for now...

2023-03-31 06:36 UTC, lizable commented on src/lib/backend.ai-client-esm.ts
>        return this.client.destroy(sessionId);
@Sujin-Kim1 Does it really "treat" timeout as "Infinity" in `createIfNotExists`?
`createIfNotExists` calls [`wrapWithPromise`](https://github.com/lablup/backend.ai-webui/blob/07f27fc1974abc25fa2adfdb28644c5e9d651803/src/lib/backend.ai-client-esm.ts#L951), and It inside the `wrapWithPromise` eventually calls `setTimeout` which doesn't treat `Infinity` as is.
Could you check it again?

2023-03-31 06:37 UTC, lizable requested changes
I left a comment related to `setTimeout()` function.

2023-04-01 11:00 UTC, adrysn requested changes
This doesn't resolve this issue. Installing images still waits until timeout.

2023-04-01 12:11 UTC, adrysn commented
I updated the code. Please test and review. @Sujin-Kim1

2023-04-02 13:45 UTC, merged