feature: rename usage tab and add info dialog in statistics page
lablup/backend.ai-webui pull request #1692
Opened 2023-04-21 08:56 UTC by Sujin-Kim1

resolves https://github.com/lablup/giftbox/issues/337
<img width="388" alt="image" src="https://user-images.githubusercontent.com/28584164/233592506-af9ac67b-8465-4e6a-8951-3300d993a2f9.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/28584164/233592532-69b31905-ad23-43aa-824e-5f2ac6272e76.png">

2023-04-21 13:39 UTC, adrysn requested changes
I have minor comments on the description of I/O stats.

Also, I think it is hard to know if I can open a dropdown menu since there is no background color or borderline in `vaadin-select` components (the top project select box as well). In my opinion, it might be better to clearly distinguish the components as clickable menus, not just text.

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/7539358/233650015-faffdda1-f987-487c-b780-dd584dde8c0f.png">

2023-04-21 13:39 UTC, adrysn commented on resources/i18n/ko.json
> +    "IOWriteDesc": "IO로 전송된 데이터의 양입니다.",
IO (Input/Output) is not a device, so this expression is strange. How about:

* 연산 세션에서 읽어들인(read) 데이터의 크기입니다. 단, 데이터 폴더 등 외부에서 마운트 된 장치에서 읽어들은 데이터 양은 포함되지 않습니다.
* 연산 세션에서 기록한(write) 데이터의 크기입니다. 단, 데이터 폴더 등 외부에서 마운트 된 장치에서 생성한 데이터 양은 포함되지 않습니다.

2023-04-25 03:46 UTC, yomybaby reviewed
@Sujin-Kim1   How about moving the note from bottom of Info modal to the top? It might be better to first inform users that only terminated session logs are displayed.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/621215/234169703-d8685d96-6e68-4b13-9fd5-a23758678313.png">

2023-04-25 07:53 UTC, agatha197 commented on resources/i18n/ko.json
> +    "IOWriteDesc": "IO로 전송된 데이터의 양입니다.",
Thanks for the kind feedback! I reflected them.

2023-04-25 07:54 UTC, Sujin-Kim1 commented
> kimsujin (@Sujin-Kim1) How about moving the note from bottom of Info modal to the top? It might be better to first inform users that only terminated session logs are displayed. <img alt="image" width="766" src="https://user-images.githubusercontent.com/621215/234169703-d8685d96-6e68-4b13-9fd5-a23758678313.png">

I removed the note to the top! Please check again :)

2023-04-27 06:27 UTC, adrysn approved these changes
LGTM.

2023-04-27 06:30 UTC, merged