feat: ui prototype of session launcher neo
lablup/backend.ai-webui pull request #1896
Opened 2023-08-30 04:32 UTC by yomybaby

2023-09-26 02:54 UTC, agatha197 requested changes
<img width="301" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/839c1dd3-e3a7-4556-8cbc-62d1299af477">
The English translation is strange.

2023-09-26 06:50 UTC, agatha197 requested changes
Let's unify the style. (Table in the Card component)
without `bordered`
<img width="1018" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/8ef174db-9e35-46d6-af12-4ea96a8e2cd6">
with `bordered`
<img width="722" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/08f7d0bb-56a2-4fcf-815a-fc2313376647">

2023-09-26 12:41 UTC, yomybaby commented
@agatha197  Thank you. I pushed two commits to resolve what you mentioned. Please review again.

2023-09-26 15:10 UTC, agatha197 commented
@yomybaby please resolve the conflict :)

2023-09-27 02:30 UTC, yomybaby commented
@agatha197 Oops. I resolved conflicts.

2023-10-04 07:45 UTC, agatha197 requested changes
How about setting the width of setting card according to the screen size? In progress 3, the horizontal scrolling is inevitable.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/e3907cc2-a25c-4075-82f7-b2735d484fe1)

2023-10-04 07:45 UTC, agatha197 commented on resources/i18n/ko.json
> +      "preopen": "__NOT_TRANSLATED__"
```suggestion
      "preopen": "사전 개방 포트"
```

2023-10-04 07:45 UTC, agatha197 commented on resources/i18n/en.json
> +      "PreOpenPortRangeGuide": "PreOpenPortRangeGuide",
```suggestion
      "PreOpenPortRangeGuide": "Enter multiple values separated by either a comma (,) or a space.",
```

2023-10-04 08:21 UTC, agatha197 approved these changes
LGTM

2023-10-04 08:23 UTC, merged