feat: add an auto selected volume in creating and cloning a data folder
lablup/backend.ai-webui pull request #1915
Opened 2023-09-07 08:14 UTC by agatha197

- resolves https://github.com/lablup/giftbox/issues/502
- Add 'auto' vhost when creating or cloning a data folder.
- The auto-selected folder is the lowest usage folder.
- If the usage percentage of the vhost is empty, set auto-selected vhost to the default folder.

## Screenshots
- create `autoSelectedVhostFolder` folder with auto host.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/6edaca5c-640b-468c-92b2-77f17a451dc0)
- The auto-selected folder is set to the ceph which is the lowest usage.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/38c2eed9-ba32-4b0e-8beb-b9e980b3411d)
- But after creating a new folder, the original host name (ceph) will be displayed on the storage list.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/4cae4f35-6108-45d9-9a95-8b7ef20ae5e3)
- Info description. The usage info will follow the original host's (ceph).
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/a618f955-8ee6-47db-930c-575a5a4f7a3c)

2023-09-09 13:42 UTC, adrysn requested changes
Let's specify which volume is automatically selected like the image below:
![image](https://github.com/lablup/backend.ai-webui/assets/7539358/b05e3075-33fc-4dcb-b25f-9a57037b0344)

2023-09-09 13:42 UTC, adrysn commented on resources/storage_metadata.json
> +      "description": "Automatically select the host with the least usage among the accessible folders for users. This prevents the folders from being concentrated on a single host.",
Let's rewrite:
> Choose the host with the lowest usage from the available host volumes for users. This ensures that usage is evenly distributed across multiple storage volumes, avoiding over-concentration on any single volume.

2023-09-11 04:43 UTC, agatha197 commented
> Let's specify which volume is automatically selected like the image below: ![image](https://user-images.githubusercontent.com/7539358/266784048-b05e3075-33fc-4dcb-b25f-9a57037b0344.png)

Thanks for the feedback. That's a great idea. I reflected as below.
<img width="433" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/c54f3946-da1a-400f-a70c-db1d9f12c14a">

2023-09-11 17:09 UTC, adrysn reviewed
LGTM.

2023-09-11 17:10 UTC, adrysn approved these changes

2023-09-13 00:51 UTC, merged