feature: Registry management UI using GraphQL
lablup/backend.ai-webui pull request #1975
Opened 2023-10-18 12:54 UTC by yomybaby

resolve #1894

2023-10-19 07:25 UTC, yomybaby commented on src/components/backend-ai-environment-view.ts
> +                `}
for backwards compatibility, 
- `backend-ai-registry-list`: the previous version which uses `config` REST API
- `backend-ai-react-container-registry-list`: the new version which uses GraphQL

2023-10-19 07:37 UTC, yomybaby commented
I'll update `schema.graphql` after the PRs that related to this.

2023-10-24 06:59 UTC, agatha197 requested changes
I found an error.
1. create a new registry
2. set password without username.
3. if refresh ->  that registry is deleted.
    if modify -> error occurred.

---
Can you add a warning message? If a user enters a harbor project type that requires an ID and password, such as `testing`, in cr.backend.ai, but there is no ID and password information, that occurs an unexpected error.

---
Let's add a `contextHolder` to message component to avoid a warning message.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/6266cb69-7900-4e63-937e-197d0f0a85aa)

ref
- antd: https://ant.design/components/message
- control panel
  - https://github.com/lablup/backend.ai-control-panel/pull/683/files#diff-85da2aab8b5207bb4d1a51c90becd03773c4b6c176f2fc87a6e008d046ebf318R29
  - https://github.com/lablup/backend.ai-control-panel/pull/683/files#diff-85da2aab8b5207bb4d1a51c90becd03773c4b6c176f2fc87a6e008d046ebf318R72
  - https://github.com/lablup/backend.ai-control-panel/pull/683/files#diff-85da2aab8b5207bb4d1a51c90becd03773c4b6c176f2fc87a6e008d046ebf318R208

2023-10-24 09:55 UTC, yomybaby commented
I update below:
- If `hobor` is selected without id/pw, show confirm when click saving.
- if a password exists, username rule has a required option
  <img width="501" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/eb82814a-14ef-44ba-b0aa-85c3869216fa">
- use `useMessage` (because `App` doesn't work properly)

2023-10-25 03:07 UTC, agatha197 requested changes
Cannot create a new registry this way.
1. Fill hostname, registry URL, password
2. Click Add button
3. remove input string of password
4. Click Add button
5. `Error Occurred` notification is shown.

2023-10-26 06:22 UTC, agatha197 approved these changes
LGTM!

2023-10-26 06:38 UTC, merged