feature: show up only model store project when vfolder type is model
lablup/backend.ai-webui pull request #2069
Opened 2023-12-01 05:14 UTC by lizable

This PR resolves showing up new type of project (`MODEL_STORE`) in vfolder creation so that user could create model type vfolder on corresponding project.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [x] Minimum required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [x] Test case(s) to demonstrate the difference of before/after

### Tests
> Prerequisites:
> - Set the core branch to the latest commit of [feature/model-card-ui](https://github.com/lablup/backend.ai/pull/1749)
> - Add model-type of vfolder in project by using backend.ai CLI below (you need to login first)
     ```
     $ ./backend.ai vfolder create -g model-store --usage-mode model testmodel local:volume1
     ```
     (This command will create project "model-store" and model type vfolder names "testmodel" )

※ NOTE: Only admin user can create group vfolder

- [ ] Check whether you can create "General" usage mode vfolder with both user/group type.
- [ ] Check whether you can create "MODEL_STORE" usage mode vfolder with both user/group type.
- [ ] Check "MODEL_STORE" usage mode vfolder is visible in models tab.

2023-12-01 06:18 UTC, yomybaby requested changes

2023-12-01 06:18 UTC, yomybaby commented on src/lib/backend.ai-client-esm.ts
> +    type = ["GENERAL", "MODEL_STORE"],
For better compatibility, it's better to add a new argument as the last argument.

2023-12-01 10:01 UTC, agatha197 approved these changes
LGTM

2023-12-04 06:20 UTC, yomybaby approved these changes
LGTM

2023-12-04 06:43 UTC, agatha197 approved these changes
LGTM

2023-12-04 22:16 UTC, merged