feat: Add table columns setting component
lablup/backend.ai-webui pull request #2071
Opened 2023-12-04 00:33 UTC by gee05053

This PR resolves https://github.com/lablup/backend.ai-webui/issues/2056

**TaskList**

- [ ] Apply BAIModal
- [ ] Apply table columns to align vertically
- [ ] Table columns search
- [ ] Apply table column's title to change React Node to string
- [ ] Change table column's order
- [ ] Fixed table columns

![스크린샷 2023-12-04 오전 9 24 21](https://github.com/lablup/backend.ai-webui/assets/28584221/37386fd7-91bf-47f2-95c7-d185933335d1)

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2023-12-08 05:31 UTC, agatha197 requested changes
Let's change 'Routing Count(Active/Total)' to 'Routing Count' and add a button to check all items. You can use [intermediate button](https://ant.design/components/checkbox#components-checkbox-demo-check-all) or [TreeSelect](https://ant.design/components/tree-select#tree-select-demo-checkable). And please resolve the conflicts :)

2023-12-13 02:37 UTC, yomybaby requested changes

2023-12-13 02:37 UTC, yomybaby commented on react/src/components/TableColumnsSettingModal.tsx
> +              </Card>
It's better to remove Card.

2023-12-13 02:37 UTC, yomybaby commented on react/src/components/TableColumnsSettingModal.tsx
> +    <BAIModal
Please set the minimum height of the Modal to prevent the modal size from changing when the user types a filter.

2023-12-13 02:40 UTC, yomybaby requested changes

2023-12-13 02:40 UTC, yomybaby commented on react/src/components/TableColumnsSettingModal.tsx
> +          <Input
Please, set a placeholder.

2023-12-13 08:50 UTC, merged