feat:embed functional HTML elements within notice.
lablup/backend.ai-webui pull request #2098
Opened 2023-12-13 08:13 UTC by gee05053

This PR resolves https://github.com/lablup/giftbox/issues/570
![스크린샷 2023-12-13 오후 5 05 07](https://github.com/lablup/backend.ai-webui/assets/28584221/f7252167-8ea2-4a1c-8491-632845795558)

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2023-12-14 01:57 UTC, agatha197 reviewed
Please reduce the width of x scrollbar too!
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/3fb393f1-5753-4ec1-bff6-f8c133b4d528)

2023-12-14 01:57 UTC, agatha197 commented on src/components/backend-ai-summary-view.ts
> +                style="overflow:auto"
```suggestion
                style="overflow:auto;"
```

2023-12-14 01:57 UTC, agatha197 requested changes
Please reduce the width of x scrollbar too!
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/3fb393f1-5753-4ec1-bff6-f8c133b4d528)

2023-12-21 01:26 UTC, yomybaby requested changes
It's better that use can see a whole notice message without scrolling. @gee05053

2023-12-22 10:34 UTC, yomybaby approved these changes
I pushed some changes. please check @gee05053 
it works properly now. I'll merge. Thank you

2023-12-22 10:35 UTC, merged