refactor: React root
lablup/backend.ai-webui pull request #2121
Opened 2023-12-28 02:56 UTC by yomybaby

This PR modifies the structure to have React as the root, with the existing backend.ai-webui components nested within. This change includes managing the Main layout, which corresponds to the Sider and Menu, within React.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-01-17 00:44 UTC, yomybaby commented
👍 @agatha197  I think we are almost finished. 
We are making many changes in this PR, so we need to test it carefully.
Please add a PR checkpoint to the PR description for the reviewer.

2024-01-22 09:16 UTC, yomybaby commented
~~When i18n language is changed, the page title on the Header wasn't changed. (I'll fix this)~~ FIXED.
<img width="1476" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/26dd1eb3-73c5-4111-9d26-347bff149685">

2024-01-22 11:42 UTC, yomybaby commented
Push commits:
- Reduce the sider width 
- Fix slider collapsing condition

2024-01-22 11:43 UTC, yomybaby commented
Push commits:
- Reduce the sider width 
- Fix slider collapsing condition

2024-01-23 05:51 UTC, yomybaby commented
Oops. The serving detail page is missing. I'll fix it.

2024-01-23 08:55 UTC, gee05053 requested changes
![스크린샷 2024-01-23 오후 5 44 29](https://github.com/lablup/backend.ai-webui/assets/28584221/3d76542a-905d-473e-8b89-f1329fa0d099)
![스크린샷 2024-01-23 오후 5 50 47](https://github.com/lablup/backend.ai-webui/assets/28584221/ad71e033-009b-40f5-9bb6-6e8aa2a0ed05)

@yomybaby 
tab's color is strange.

2024-01-23 09:05 UTC, agatha197 commented
> ![스크린샷 2024-01-23 오후 5 44 29](https://private-user-images.githubusercontent.com/28584221/298871185-3d76542a-905d-473e-8b89-f1329fa0d099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDA5NjksIm5iZiI6MTcwNjAwMDY2OSwicGF0aCI6Ii8yODU4NDIyMS8yOTg4NzExODUtM2Q3NjU0MmEtOTA1ZC00NzNlLThiODktZjEzMjlmYTBkMDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZjFhOWNiNWI2ZThkYzJmMjRiZmQ1MTQ2YmVmY2U5MzcxNTY3OTAyYjY0ODAwOTE2Njc2MTczMDcwZGVhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFdJmD-X5asigUK3LahW_Yp8xwwKALWxjdPiVfsiifQ) ![스크린샷 2024-01-23 오후 5 50 47](https://private-user-images.githubusercontent.com/28584221/298871227-ad71e033-009b-40f5-9bb6-6e8aa2a0ed05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDA5NjksIm5iZiI6MTcwNjAwMDY2OSwicGF0aCI6Ii8yODU4NDIyMS8yOTg4NzEyMjctYWQ3MWUwMzMtMDA5Yi00MGY1LTliYjYtNmU4YWEyYTBlZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTFkYmFhZDFmYTBmMjZiY2NjNmIxNjgzMGFhNTc5MWI5N2U2ZGRmNmI5ZTQ4OTA4YTgyMTg1YzA0YmRjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RxZgXqwnp8midoaCxEOWb85pdAZzz9aLBudkd_nQxX8)
> 
> @yomybaby tab's color is strange.

oops, my mistake. I'll handle it.

2024-01-24 04:02 UTC, gee05053 requested changes
@agatha197 I added to tasklist.

Bug: user can navigate to use dropdown menu or webui logo even though page is added in blocklist and inactivelist

2024-01-24 04:02 UTC, gee05053 commented on src/components/backend-ai-maintenance-view.ts
> +    let taskId;
@agatha197 taskId is unused variable

2024-01-24 04:19 UTC, ironAiken2 requested changes
On the Agent Summary page, the UI changes for each network request.
1. After resizing the cell, the size will change randomly as the network request progresses.
2. The phrase "No Agents to display" will be re-rendered on each network request.

Additionally, the default cell width is different when there is a list value and when it is empty.

<img width="1061" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/e0e4427f-1579-46ae-b54d-f2a5b2d3e80b">
<img width="1061" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/3b70f74e-c0b4-4760-b2b6-d7ee3f8a38b1">

<img width="1058" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/0af53b31-2692-44b8-8254-2d50113ff987">

2024-01-24 05:30 UTC, gee05053 commented
@yomybaby 
After an error occur, notification is not shown correct content

![스크린샷 2024-01-24 오후 2 15 02](https://github.com/lablup/backend.ai-webui/assets/28584221/0e5d6530-d138-4215-8e6f-98363b056a79)

2024-01-24 07:41 UTC, gee05053 commented
@yomybaby @agatha197 
only electron occur.
when user login and summary page is appeared, sidebar is not select.
![스크린샷 2024-01-24 오후 4 35 49](https://github.com/lablup/backend.ai-webui/assets/28584221/6ca59cd7-b20b-4c0f-b50f-47202f0911b3)

2024-01-24 08:23 UTC, ironAiken2 requested changes
Only occurs in an electron environment. An error occurs on logout.

@yomybaby @agatha197 
<img width="1495" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/726706d2-2c94-44a9-852f-508ecfc2588b">

2024-01-24 09:08 UTC, ironAiken2 requested changes
Only occurs in an electron environment. 

If you customize the filtering criteria in TableColumnsSettingModal and press OK, the data will be filtered correctly, but when you reopen the modal, the selected criteria will not be applied. If you reopen the modal one more, then will be applied.

@yomybaby @agatha197 

![image](https://github.com/lablup/backend.ai-webui/assets/51399982/1a30762f-8bd4-4d4e-a535-ca4b89c90f9c)
![image](https://github.com/lablup/backend.ai-webui/assets/51399982/f2fd7647-7731-47dc-a955-2897f9c0c222)

2024-01-26 06:11 UTC, gee05053 requested changes
@yomybaby 
I found issue after you added detail button in error notification.
It work correctly at error notification.
But if you click error notification's detail button in notification drawer, you navigate to `usersetting` page
![스크린샷 2024-01-26 오후 3 03 37](https://github.com/lablup/backend.ai-webui/assets/28584221/7319b4ab-bf51-41a0-826b-4fb9c0ec7212)
![스크린샷 2024-01-26 오후 3 04 13](https://github.com/lablup/backend.ai-webui/assets/28584221/0b920dc4-a977-43e8-9c86-06c30cd0c87f)

2024-01-29 03:15 UTC, gee05053 approved these changes
LGTM😊

2024-01-29 03:26 UTC, merged