feat: add support for Hyperaccel LPU devices
lablup/backend.ai-webui pull request #2134
Opened 2024-01-08 05:12 UTC by kyujin-cho

This PR updates webui to support querying, altering and attaching Hyperaccel LPU devices.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-01-19 03:05 UTC, inureyes requested changes
Device icon needs to change from furious to hyperaccel icon.

2024-01-19 03:05 UTC, inureyes commented on resources/device_metadata.json
> +      "display_icon": "furiosa"
Need to change icon?

2024-01-23 01:37 UTC, rapsealk commented on react/src/components/ResourceNumber.tsx
> +    'lpu.device': ['/resources/icons/furiosa.svg', 'LPU'],
```suggestion
    'lpu.device': ['/resources/icons/hyperaccel.svg', 'LPU'],
```

2024-01-23 01:37 UTC, rapsealk commented on react/src/hooks/useResourceLimitAndRemaining.tsx
> +            'lpu.device': 'maxWarboyDevicesPerContainer', // FIXME: add maxWarboyDevicesPerContainer to config
```suggestion
            'lpu.device': 'maxLPUDevicesPerContainer', // FIXME: add maxLPUDevicesPerContainer to config
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-agent-list.ts
> +                      src="/resources/icons/furiosa.svg"
```suggestion
                      src="/resources/icons/hyperaccel.svg"
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-agent-summary-list.ts
> +                      src="/resources/icons/tpu.svg"
```suggestion
                      src="/resources/icons/hyperaccel.svg"
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-session-launcher-neo.ts
> +                available_slot['cuda_device'],
```suggestion
                available_slot['lpu_device'],
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-session-launcher-neo.ts
> +                parseInt(available_slot['cuda_device']),
```suggestion
                parseInt(available_slot['lpu_device']),
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-session-launcher.ts
> +                parseInt(available_slot['cuda_device']),
```suggestion
                parseInt(available_slot['lpu_device']),
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-session-launcher.ts
> +                available_slot['cuda_device'],
```suggestion
                available_slot['lpu_device'],
```

2024-01-23 01:37 UTC, rapsealk commented on src/components/backend-ai-session-list.ts
> +                      src="/resources/icons/furiosa.svg"
```suggestion
                      src="/resources/icons/hyperaccel.svg"
```

2024-03-28 07:44 UTC, lizable commented on src/components/backend-ai-settings-view.ts
> +                    >
We need translations

2024-03-28 07:57 UTC, lizable commented on src/components/backend-ai-resource-panel.ts
> +                                          'summary.LPUEnabled',
Here as well.

2024-03-28 07:59 UTC, yomybaby commented on src/components/backend-ai-settings-view.ts
> +                    >
![Uploading image.png…]()

2024-03-28 08:10 UTC, lizable reviewed
Found some missing translations, and minor icon matching. Except that, it's okay to merge.

2024-03-28 08:31 UTC, lizable approved these changes
LGTM.

Btw we'd better add those AI accelerators(including Hyperaccel LPU and others) into resource policy as well.

2024-04-01 03:34 UTC, lizable approved these changes
LGTM.

2024-04-05 02:21 UTC, inureyes commented
LGTM. 

We need to continue https://github.com/lablup/backend.ai-webui/pull/1937 ( ref. @lizable @kyujin-cho @agatha197 )

2024-04-05 02:21 UTC, inureyes approved these changes

2024-04-05 02:22 UTC, merged