fix:modify guide description of TOTPActivateModal and add rule of OTP input
lablup/backend.ai-webui pull request #2174
Opened 2024-01-25 04:49 UTC by gee05053

This PR resolves https://github.com/lablup/backend.ai-webui/issues/2163

I modified guide description of TOTPActivateModal.
Also I added rule that user can write only number in OTP input and form.validateFields.catch().

![스크린샷 2024-01-25 오전 11 31 01](https://github.com/lablup/backend.ai-webui/assets/28584221/6515808a-8435-4bc1-9999-7280ecd7508b)
![스크린샷 2024-01-25 오후 1 29 17](https://github.com/lablup/backend.ai-webui/assets/28584221/ce9d7fa9-9e80-4c25-8f65-8c994e0861eb)
![스크린샷 2024-01-25 오후 1 44 03](https://github.com/lablup/backend.ai-webui/assets/28584221/4ef30856-3eb9-429f-866e-67918420a0f7)

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-02-01 22:56 UTC, yomybaby commented
@agatha197  Please review this. Thank you.

2024-02-05 07:01 UTC, agatha197 requested changes

2024-02-05 07:01 UTC, agatha197 commented on react/src/components/TOTPActivateModal.tsx
> +                    message: t('credential.validation.NumbersOnly'),
Let's separate warning message. 
1. Case for empty string
2. Case for pattern mismatching.

2024-02-05 09:24 UTC, agatha197 approved these changes
LGTM

2024-02-05 09:26 UTC, merged