feat: autoSelectDefault and showUsageStatus props of StorageSelector
lablup/backend.ai-webui pull request #2180
Opened 2024-01-26 07:03 UTC by ironAiken2

### This PR resolves #2151
changes: 
- upgrade antd into latest version.
: when I checked release note, our project is not using disposed property and new property on select are clearly useful. 

feature:
- autoSelectDefault
: "true" for auto-selecting a value (default value in vhostInfo), "false" for disabling the feature. (means no value and show placeholder text). 
- showUsageSelect
: "true" for showing usage in each host, "false" for disabling the feature.
: If use this props with autoSelectDefault that is "true", the default selected values is depending on usage status.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-01-26 07:13 UTC, ironAiken2 commented
But I thing that the upgrading version issue covers a large area and should be fixed by addressing the issue in the current version of the project.

2024-01-26 08:56 UTC, yomybaby requested changes

2024-01-26 08:56 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +          <Space>
Please use 'Flex' instead of `<Space/>` if available.

2024-01-26 08:56 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +              <div
How about '[Badge](https://ant.design/components/badge#badge-demo-status)'?

2024-01-26 08:56 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +  value,
Let's use [ahooks's useControllerbleValue](https://ahooks.js.org/hooks/use-controllable-value)

2024-01-26 08:56 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +      <Select
Form controls such as Select, Input, etc should return one element for `Form.Item`.

2024-01-31 09:22 UTC, lizable commented on react/src/components/StorageSelect.tsx
> +              status={status[idx]}
We already have color setting function in index. Please refer to this code below and update Badge component props.
https://github.com/lablup/backend.ai-webui/blob/ff29a586a1e7af517289fa1999450692f638282e/react/src/helper/index.tsx#L227-L233

2024-01-31 09:22 UTC, lizable commented on react/src/components/StorageSelect.tsx
> +    const status = ['success', 'warning', 'error'];
And I think it's not necessary if we use color instead.

2024-02-01 09:01 UTC, lizable approved these changes
I just found some minor test failures in github action, originated from dependency array in hooks([useEffect](https://github.com/lablup/backend.ai-webui/pull/2180/files/a8537491593776c31e4485e01c4163b2d5fd87e5#diff-bec9f3b247068290d015fe25aac131df101c7055e4a8d8276085abd1f90ed04cR86) and [useMemo](https://github.com/lablup/backend.ai-webui/pull/2180/files/a8537491593776c31e4485e01c4163b2d5fd87e5#diff-bec9f3b247068290d015fe25aac131df101c7055e4a8d8276085abd1f90ed04cR66)). You could either follow the guidance from github action or just input right above the line if there has certain reason (https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528).

2024-02-01 09:09 UTC, lizable requested changes
Please resolve test failure on github action following the comments above.

2024-02-01 16:01 UTC, ironAiken2 commented
I thought the "vhostInfo" data is used directly within the useEffect, and changes in it have a significant impact on determining the selectd host. So I added vhostInfo to the dependencies array. 

However, the other items are only configurable in code, so I removed them from the Dependencies array because I thought they were less likely to be changed because the user can't change their settings.

2024-02-06 02:15 UTC, lizable approved these changes
LGTM.

2024-02-08 03:03 UTC, yomybaby requested changes

2024-02-08 03:03 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +    console.log('!');
Please remove this line.

2024-02-08 03:03 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +        direction: 'ltr',
Is there any reason to set the direction here?

2024-02-08 03:03 UTC, yomybaby commented on react/src/components/StorageSelect.tsx
> +                getPopupContainer={() => shadowRoot}
I push a commit to add a tooltip with `getPopupContainer`. Please add a proper text for each case. @ironAiken2

2024-02-08 08:12 UTC, yomybaby commented
I pushed commits to display search highlights and update type definition. @ironAiken2 , Please check.
I merged this PR. Thank you!

2024-02-08 08:12 UTC, merged