fix: credential-lists is displayed when admin click `create keypair` or `manage keypair` in `summary` page
lablup/backend.ai-webui pull request #2194
Opened 2024-01-31 03:05 UTC by gee05053

This PR resolves https://github.com/lablup/backend.ai-webui/issues/2175

After this PR, it is need to implement antd's tab instead of using mwc-tab and add routing each tab.
 
![스크린샷 2024-01-31 오후 12 00 52](https://github.com/lablup/backend.ai-webui/assets/28584221/bba90ca9-a6f4-41e7-ad81-bd6d6104debb)
![스크린샷 2024-01-31 오후 12 01 03](https://github.com/lablup/backend.ai-webui/assets/28584221/fd425152-8c94-4de5-9c6c-94259892af18)

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-02-05 09:53 UTC, agatha197 requested changes

2024-02-05 09:53 UTC, agatha197 commented on src/components/backend-ai-credential-view.ts
> +    } else if (location.search.includes('manage')) {
It is awkward to handle `manage` related codes in the `_runAction()`.
Let's rename the function name or separate them.

2024-02-08 03:19 UTC, yomybaby commented
@agatha197 Please review this PR again. 🙏

2024-02-08 04:57 UTC, agatha197 approved these changes
LGTM

2024-02-08 05:45 UTC, merged