feat: support vfolder trash bin
lablup/backend.ai-webui pull request #2204
Opened 2024-02-06 10:19 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-02-08 03:49 UTC, yomybaby commented
I'll review this PR after merging https://github.com/lablup/backend.ai/pull/1892 @agatha197

2024-02-23 10:14 UTC, yomybaby requested changes

2024-02-23 10:14 UTC, yomybaby commented on src/components/backend-ai-storage-list.ts
> +          <mwc-button raised @click="${() => this._deleteForever()}">
<img width="206" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/144ca403-ba5a-4e42-96d0-f7c4b6169bd7">

Please change the color of "영구삭제" button to destroy color.

2024-02-23 10:14 UTC, yomybaby commented on src/components/backend-ai-storage-list.ts
> +  _deleteForever() {
How about matching the names related to "deleteForever" to API name "delete-from-trash-bin" ? `deteFromTrashBin`

2024-02-23 10:19 UTC, yomybaby commented
<img width="395" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/bda12822-b67d-4b94-8b7d-cddda8c3a42a">

<img width="366" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/227006a0-c97e-44fa-b448-95687f5ad23f">

Since supporting the trash bin, the 'delete from trash bin' action needs to be confirmed by the user.

2024-02-23 11:49 UTC, agatha197 commented
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/621215/307289094-bda12822-b67d-4b94-8b7d-cddda8c3a42a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM4NzEsIm5iZiI6MTcwODY4MzU3MSwicGF0aCI6Ii82MjEyMTUvMzA3Mjg5MDk0LWJkYTEyODIyLWI2N2QtNGI5NC04YjdkLWNkZGRhOGMzYTQyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDNjZDQ4NzdlZjQxZjVkNzE0MTIwMzFlYjlkYjVjNDJiYmJjZDUzOGM2MDgyNjM4M2RiZTdhZDYwMDRjYTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0UNcApY35UAT1JSMDCP3Yw65VOQJsqwMTf1oHaB_K1w"> <img alt="image" width="366" src="https://private-user-images.githubusercontent.com/621215/307288587-227006a0-c97e-44fa-b448-95687f5ad23f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM4NzEsIm5iZiI6MTcwODY4MzU3MSwicGF0aCI6Ii82MjEyMTUvMzA3Mjg4NTg3LTIyNzAwNmEwLWM5N2UtNDRmYS1iNDQ4LTk1Njg3ZjVhZDIzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTU1Yzk3YjFkNTExMzJmNmQzNmMyOWQ5NTFiMTE4YmZkZjRlMDU0OTAyZjIyYjg1NWNhMzNhMjYwMTQwNDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.An9oOAPkX0qmxCyyvnNTSETkABl3BtBWMOZ4YCsV1ds">
> Since supporting the trash bin, the 'delete from trash bin' action needs to be confirmed by the user.

Thank you for your feedback! I modified as below :)
<img width="652" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/86c81592-78b4-4763-b04f-93efd0c0a83f">

2024-02-28 05:56 UTC, yomybaby commented
@agatha197 Please resolve conflicts.

2024-02-28 10:53 UTC, agatha197 commented
> kimsujin (@agatha197) Please resolve conflicts.

Done!

2024-03-28 08:30 UTC, yomybaby requested changes
If manager supports `vfolder-trash-bin`: 

- Tooltip: "Delete" to "Move to trash bin"
    <img width="339" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/b559f3aa-b4e5-4624-bf36-f148e4ae3325">

- The confirmation modal below is not needed. However, the notification message should describe "휴지통으로 이동되었습니다."
    <img width="421" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/114eac29-7792-4145-9dfd-c1e6ebd067ec">
    <img width="421" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/b377949d-e7f1-42e5-b87b-e646bc011ebc">

2024-03-28 08:33 UTC, yomybaby requested changes
- How about changing the trash bin icon color to the normal color since "move to trash bin" is not a dangerous action?
<img width="582" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/7e8af3cd-e9d4-44ca-af89-fa31c30d5433">

2024-04-01 03:14 UTC, yomybaby commented
@agatha197  Thank you for the update. It's better than before. Could you improve the messages to include the folder name?

- "휴지통으로 이동되었습니다." to "OOO 폴더가 휴지통으로 이동되었습니다."
- "폴더가 복원되었습니다." to " OOO 폴더가 복원되었습니다."
- "폴더가 완전히 삭제되었습니다." to "OOO 폴더가 완전히 삭제되었습니다."

2024-04-01 07:52 UTC, yomybaby approved these changes
LGTM

2024-04-01 08:12 UTC, merged