feat: Automate Resource Presets in Neo Session Launcher
lablup/backend.ai-webui pull request #2220
Opened 2024-02-20 02:33 UTC by yomybaby

This PR:
- handles the Neo session launcher/list by react root. Additionally, it adds a draft version of the resource group available panel and the `availableFilter` prop of ResourceAllocationFormItems.
- runs the `runShmemAutomationRule` when the preset is changed. Furthermore, it enables the allocatable resource preset only automatically. It prevents session name autocompletion and fixes the session name validation. 
- displays the infinite symbol for session limit is 1000000.
- adds a range compare helper function and test code. 
- adds tests for handling undefined limits in the `isOutsideRange(WithUnits)` function. 

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-03-13 06:59 UTC, agatha197 requested changes
## 1
Would it be better to message that the session name should not end in special characters?
<img width="674" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/a9daa216-f765-4984-b8ce-8cf682f5b647">

## 2
It's better to automatically modify the custom input value like the number of sessions.
1. I got the error message when I wrote 0 to CPU at first.
	<img width="355" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/bf82057e-2fb0-476e-b996-5afe8dbb4888">

2. But it automatically changes to the minimum value of 1 when I put the mouse on the input and then turn it off again.
	<img width="343" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/bd6ed0b4-4519-4c59-a167-5650890c8dad">


On the other hand, the sessions number is automatically changed to 1 which is the minimum value.
<img width="421" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/5d5bcc31-5ccb-4dcf-962d-69b6c2366304">

## 3
The left time of starting the batch session is shown with delay. How about using `BatchSessionScheduledTimeSetting`  like original session launcher?
<img width="315" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/1b8c19f9-f314-4f5f-b966-80ac617ba1bc">

This is the previous session launcher's scheduled time selector.
<img width="307" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/4f05fad8-8d08-4a22-9725-994137f699fa">

2024-03-13 06:59 UTC, agatha197 commented on react/src/components/NeoSessionLauncherSwitchAlert.tsx
> +                  label: t('session.launcher.PreviousLauncher'),
```suggestion
                  label: (
                    <Typography.Text
                      style={{
                        color: !is2409Launcher ? undefined : token.colorPrimary,
                      }}
                    >
                      {t('session.launcher.PreviousLauncher')}
                    </Typography.Text>
                  ),
```

<img width="539" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/3c39a6e9-e81b-4116-a6ef-2f607e6e1576">

↓
<img width="1003" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/f90de0dd-5e2e-40cf-a510-6ed55af5b845">
For dark mode, I recommend changing the previous version to the default color as well :)

2024-03-13 06:59 UTC, agatha197 commented on react/src/hooks/useBAISetting.tsx
> +    setSelf(onInitialize(savedValue != null ? JSON.parse(savedValue) : null));
```suggestion
    setSelf(onInitialize(savedValue !== null ? JSON.parse(savedValue) : null));
```

2024-03-13 06:59 UTC, agatha197 commented on src/components/backend-ai-session-launcher.ts
> +      )['use_2409_session_launcher'];
```suggestion
      )['use_2403_session_launcher'];
```

2024-03-13 06:59 UTC, agatha197 commented on src/plugins.gitignore/README.md
Did you add this file on purpose?

2024-03-13 07:38 UTC, yomybaby commented on src/plugins.gitignore/README.md
I removed files. 😉

2024-03-13 07:39 UTC, yomybaby commented on react/src/hooks/useBAISetting.tsx
> +    setSelf(onInitialize(savedValue != null ? JSON.parse(savedValue) : null));
I pushed a commit to fix this.

2024-03-13 07:42 UTC, yomybaby commented on react/src/components/NeoSessionLauncherSwitchAlert.tsx
> +                  label: t('session.launcher.PreviousLauncher'),
I accept your suggestion. Thank you.

2024-03-14 02:19 UTC, agatha197 requested changes
## 4
<img width="721" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/1b9ee640-29b2-4ead-9ef0-eb5fe219e144">
If there isn't supported AI accelerator, user can see the '0' string without any suffix. It would be better to represent as a 'No accelerator' or remove it.

## 5
<img width="715" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/7e1fd522-77f3-4299-acff-2d448ab835a6">
When I set the batch session without the start command, the input field can be active. But I can't input any string. I think it's better to make readonly the input field or just represent it with strings like the session name.

## 6
I cannot confirm the setting options of `High-Performance Computing Optimizations` on the last page. Is it intended?

2024-03-26 09:21 UTC, yomybaby commented
@agatha197 [6233a8b](https://github.com/lablup/backend.ai-webui/pull/2220/commits/6233a8b55a6c44f3167889dba520010e52e8e13a) resolves your number 3 feedback.

2024-03-26 10:27 UTC, yomybaby commented
Please check recent commit to resolve your feedback 
- feedback 4: https://github.com/lablup/backend.ai-webui/pull/2220/commits/55c0609cecb136f666e7a976fda8b83931c0a2a6 
- feedback 5: https://github.com/lablup/backend.ai-webui/pull/2220/commits/bfb2df41cd078b37a88f8f2d61393cc9fe26395d

2024-03-27 07:37 UTC, yomybaby commented
@agatha197 How can I reproduce feedback 2?

2024-03-27 09:55 UTC, yomybaby commented
@agatha197  I pushed several commits related to `useBAISetting.txs` which are used by `NeoSessionLauncherSwitchAlert`.

2024-03-28 00:55 UTC, agatha197 commented
> kimsujin (@agatha197) How can I reproduce feedback 2? I think it is fixed already. Please check again. Thank you.

Drag and input 0 and click outside of the input :) I know, it's no big deal.
https://github.com/lablup/backend.ai-webui/assets/28584164/f623a7fb-af56-46b9-898b-3fd398acd4ed

2024-03-28 01:17 UTC, agatha197 commented
> Please check recent commit to resolve your feedback
> 
> * feedback 4: [55c0609](https://github.com/lablup/backend.ai-webui/commit/55c0609cecb136f666e7a976fda8b83931c0a2a6)
> * feedback 5: [bfb2df4](https://github.com/lablup/backend.ai-webui/commit/bfb2df41cd078b37a88f8f2d61393cc9fe26395d)
> * feedback 6: The previous session launcher doesn't display "High-Performance Computing Optimizations" in the last step. Should we add it?

Ah, I checked it. We don't need to.

2024-03-28 01:30 UTC, agatha197 requested changes
## 7
Can you make the startup command to the center?
<img width="727" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/540e1ea0-b3e0-4f68-abbf-84ee2a577418">

## 8
In the batch session, if the start time is not set, we don't care about it. The session ends after running the startup command. 
But even if I didn't set the start time, the start time seems like being set on the last page. So it's better to represent the start time as '-'.

2024-03-28 02:00 UTC, yomybaby commented
Response of Feedback 7 & 8:
In the last step, if there is no input, the item will display the text `None` with the secondary style. https://github.com/lablup/backend.ai-webui/pull/2220/commits/e620228e26a96600bd1245c6334e2c7e8226435c
<img width="730" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/554c6cc2-947a-45a0-a558-52dda99976ab">
<img width="718" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/6583e606-2db5-4c5d-8b8f-27beb1e4f3d8">

2024-03-28 02:22 UTC, yomybaby commented
https://github.com/lablup/backend.ai-webui/pull/2220/commits/7cfe5307cf1db7a269951417d1e4ffad5a1ec447 resolves the feedback 2 😉 ✌️

2024-03-28 03:40 UTC, ironAiken2 requested changes
- The environment variable value validation does not have i18n applied to it.
- The variable field in environment step performs the `required` validation on focus out with no input after focus, while a value field does not perform the `required` validation until a value is entered.

<img width="671" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/1d2151b7-5cee-4201-b1d8-8aa42e4258ef">

2024-03-28 04:46 UTC, agatha197 requested changes
https://github.com/lablup/backend.ai-webui/blob/7cfe5307cf1db7a269951417d1e4ffad5a1ec447/react/src/pages/SessionLauncherPage.tsx#L1120

Please add `column={24}` to prevent this warning.
```
warning.js:30 Warning: [antd: Descriptions] Sum of column `span` in a line not match `column` of Descriptions.`.
```

2024-03-28 09:10 UTC, yomybaby commented
> * The environment variable value validation does not have i18n applied to it.
> * The variable field in environment step performs the `required` validation on focus out with no input after focus, while a value field does not perform the `required` validation until a value is entered.
> 
> <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/51399982/317581800-1d2151b7-5cee-4201-b1d8-8aa42e4258ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU4MDYsIm5iZiI6MTcxMTYxNTUwNiwicGF0aCI6Ii81MTM5OTk4Mi8zMTc1ODE4MDAtMWQyMTUxYjctNWNlZS00MjAxLWIxZDgtOGFhNDJlNDI1OGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4NDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNjFhYzk3MjJiYzA4NjE4ZGY5MzUwMjQ1N2ExMDRkZDIyYjVjZmY3MjQ0NDliNzA4MjVhZGVlMDE0ZGVhOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0D17qqqQIrpgZMtU8-ih2eWLKTMpobcDkFBBGDTVVSw">

resolved by https://github.com/lablup/backend.ai-webui/pull/2220/commits/f5454551a109c2c705e6e360229e948aca1c85ea and https://github.com/lablup/backend.ai-webui/pull/2220/commits/a3cfb0e42f5a79d8af235009b74776a08dff876e
I could not find a reason why the value field isn't validated on the blur event. So I set the validationTrigger explicitly. @ironAiken2

2024-03-28 09:48 UTC, yomybaby commented
@agatha197  @ironAiken2 All requested changes have been resolved. Please review them again.

2024-03-29 01:39 UTC, agatha197 approved these changes
LGTM!

2024-03-29 01:42 UTC, ironAiken2 approved these changes
LGTM!

2024-03-29 02:06 UTC, merged