feat: show UUID in data page's storage status panel
lablup/backend.ai-webui pull request #2259
Opened 2024-03-12 09:36 UTC by ironAiken2

### This PR Resolves #2251 issue. 

### Feature
- show quota scope id (user id) in storage status panel.
- change antd's descriptions column because 2 line representation is visually better than 3 line representation.
(I've tried showing text at the bottom of the card without using descriptions.item, but it doesn't feel consistent.)

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-03-13 08:58 UTC, yomybaby requested changes

2024-03-13 08:58 UTC, yomybaby commented on react/src/components/StorageStatusPanel.tsx
> +  const descriptionItem: DescriptionsProps['items'] = [
Please rename `descriptionItem` to `descriptionItems` because it's array.

2024-03-13 08:58 UTC, yomybaby commented on react/src/components/StorageStatusPanel.tsx
> +      key: '1',
Please change keys to more contextual names. Using `1` can easily lead to duplication and can be difficult to manage if ordering is required.

2024-03-25 07:01 UTC, lizable approved these changes
LGTM.

2024-03-26 02:52 UTC, yomybaby approved these changes
LGTM

2024-03-26 02:52 UTC, merged