feat: Neo Session Launcher Tour Guide via 'antd tour'
lablup/backend.ai-webui pull request #2284
Opened 2024-04-01 05:24 UTC by ironAiken2

### This PR Resolves #2260 Issue.

### Feature:
- Provide Tour Guide for `Neo Session Launcher`

<img width="1174" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/7a819bff-d88e-4dd8-9138-0e139249f52b">

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-04-01 06:47 UTC, yomybaby commented
It's better to show the start step in the center using `target={null}` https://ant.design/components/tour#tour-demo-placement

2024-04-01 07:54 UTC, ironAiken2 commented
[* Show the start step in the center of screen](https://github.com/lablup/backend.ai-webui/pull/2284#issuecomment-2029260860) - applied

2024-04-24 03:38 UTC, yomybaby commented
Please resolve the conflicts @ironAiken2

2024-05-08 07:50 UTC, yomybaby requested changes
There are too many steps in the tour. 
Let's keep only a few key steps and remove the rest. Let's split it into two tours: 
- Tour 1: In the first step, welcome to Neo Session Launcher, move to the right step, move to the bottom button. 
- Tour 2: Only display if there is a validation error in the final step. 
  - If there is a validation error, guide to press the modify button to correct it. 
  
And let's refactoring
- use `data-test-id` instead of using class names or refs. 
- After remaining only 2 tours, unnecessary refs can be deleted. 
- Instead of directly accessing localStorage in settings, use useBAISettingUserState. 
- Give a more specific name to the setting, indicating that it is for determining whether the tour has been completed. For example, (has_toured_neo_session_launcher_introduction):

2024-05-13 08:54 UTC, ironAiken2 commented
* **#2284** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2284?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-14 05:21 UTC, ironAiken2 commented
Applied

> There are too many steps in the tour. 
> Let's keep only a few key steps and remove the rest. Let's split it into two tours: 
> - Tour 1: In the first step, welcome to Neo Session Launcher, move to the right step, move to the bottom button. 
> - Tour 2: Only display if there is a validation error in the final step. 
>   - If there is a validation error, guide to press the modify button to correct it. 
>   
> And let's refactoring
> - use `data-test-id` instead of using class names or refs. 
> - After remaining only 2 tours, unnecessary refs can be deleted. 
> - Instead of directly accessing localStorage in settings, use useBAISettingUserState. 
> - Give a more specific name to the setting, indicating that it is for determining whether the tour has been completed. For example, (has_toured_neo_session_launcher_introduction):
> 
>

2024-05-16 04:00 UTC, yomybaby requested changes

2024-05-16 04:00 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
>                        title={t('session.launcher.SessionType')}
In this case, you can set the class name of `Card` in `BAICard` based on the `status`. Then, you won't need to set `data-test-id` with duplicated logic. Also you can query for the target of the tour step directly using calss name.
Before I told you that class name for tour purporse only is not good. However, this is a slightly different case. In this case, the class name is determined by the `status`.

2024-05-16 05:31 UTC, agatha197 requested changes
1. dark mode support is needed. (highlighting area)
<img width="300" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/bc1ae6b9-2dac-4325-b923-72ea33d901d3">
2. support i18n
3. I got TypeError. Please recheck the id.
<img width="1088" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/2a708a38-8ab3-405d-bf81-d155695c33bf">

2024-05-16 05:31 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +          '해당 오류 필드에 대해, 우측 상단의 수정 버튼으로 바로 이동하여 수정할 수 있습니다. ',
```suggestion
          '해당 오류 필드에 대해, 우측 상단의 수정 버튼으로 바로 이동하여 수정할 수 있습니다.',
```

2024-05-16 05:31 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +        description: '새로운 NEO 세션 런처에 오신걸 환영합니다!.',
```suggestion
        description: '새로운 NEO 세션 런처에 오신 것을 환영합니다!',
```

2024-05-16 05:31 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +          '우측의 단계 표시를 통해 현재 단계를 확인할 수 있습니다. 특정 단계를 클릭하여 이동할 수 있습니다.',
```suggestion
          '우측에 있는 단계 표시에서 현재 단계를 확인할 수 있습니다. 특정 단계를 클릭하여 이동할 수 있습니다.',
```

2024-05-16 05:31 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +          'Next 버튼을 통하여 다음 단계로 이동하거나 review 단계로 건너뛸 수 있습니다.',
```suggestion
          '다음 버튼을 클릭하여 다음 단계로 이동하거나 검토로 건너뛸 수 있습니다.',
```

2024-05-16 05:31 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +  );
```suggestion
```

2024-05-21 01:47 UTC, yomybaby approved these changes
LGTM

2024-05-21 01:48 UTC, yomybaby approved these changes
LGTM

2024-05-21 01:50 UTC, merged