feat: match field version compatibility for vfolder v3
lablup/backend.ai-webui pull request #2292
Opened 2024-04-02 08:28 UTC by agatha197

original issue: https://github.com/lablup/backend.ai-webui/issues/1742

## Description
- add deprecated and support variables to `_updateSupportList()` in `backend.ai-client-esm.ts`
- Show `max_vfolder_count` according to the manager version.
  - Data & Storage page - number of folders of storage status panel
  - Users - CREDENTIALS
  - Users - RESOURCE POLICIES - list and setting dialog
- update schema

Version compatibility
  | Keypair Resource Policy | Keypair Resource Policy | User Resource Policy | User Resource Policy | User Resource policy | Project Resource Policy | Project Resource Policy | Project Resource Policy
-- | -- | -- | -- | -- | -- | -- | -- | --
**VERSION** | < 23.09.4 | >= 23.09.4 | < 23.09.1 | 23.09.1 <= version < 24.03.1 | >= 24.03.1 | < 23.09.1 | 23.09.1 <= version < 24.03.1 | >= 24.03.1
max_vfolder_count | O | X | X | X | O | X | X | O
max_quota_scope_size | O | X | X | X | O | X | X | O
max_vfolder_size | O | X | O | X | X | O | X | X

## How to setup
- manager version < 23.09.4: http://10.82.230.93:8090
- 23.09.4 <= manager version < 24.03.1: http://10.82.230.94:8090
- manager version > 24.03.1: not released yet
- set `directoryBasedUsage = true` of the `config.toml` for testing.

## Checklist
- [ ] manager version < 23.09.4: **visible**
  - [ ] Data page
    - [ ] Capacity column, Folder usage - Capacity (click the info icon of the control icon) is visible.
           (* If you want to see the capacity, make sure the current host is one of the `quotaSupportStorageBackends` ('xfs', 'weka', 'spectrumscale', 'netapp', 'vast', 'cephfs','ddn') and `directoryBasedUsage` is true.)
    - [ ] Number of folders - Limit is visible.
  - [ ] User page
    - [ ] Credential tab - `max_vfolder_count` of `resource policy` column is visible
    - [ ] Resource Policies tab - `max_vfolder_count` of `resources` column / `max # of folders` when creating or modifying policy are visible.
- [ ] 23.09.1 <= manager version < 24.03.1: **invisible**
  - All the data mentioned above is invisible.
- [ ] manager version > 24.03.1: **invisible except for Number of folders - Limit**
  - [ ] In the data page, the Limit value will be `max_vfolder_count` of `user_resource_policy`.
          Except that, all data is invisible.
		https://github.com/lablup/backend.ai-webui/blob/244fb1a26aee1c9da53545ac339429fc64d0d7e3/react/src/components/StorageStatusPanel.tsx#L190-L194

</span></span>

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [x] Minium required manager version
- [x] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-04-03 04:03 UTC, yomybaby requested changes

2024-04-03 04:03 UTC, yomybaby commented on react/src/components/StorageStatusPanel.tsx
> +            {maxVfolderCount && (
if `maxVfolderCount === 0`, react display `0` instead of nothing. Does `maxVfolderCount === 0` means? `unlimited` or `0` or `-`?

2024-04-03 04:22 UTC, agatha197 commented on react/src/components/StorageStatusPanel.tsx
> +            {maxVfolderCount && (
I modified the codes. If `maxVfolderCount` is 0, display 0. And the `numberOfFolderPercent` is 100.
@yomybaby  you can test by editing the `max_vfolder_count` in Users - Resource Policy tab - Edit Max. # of folders.

2024-04-05 01:36 UTC, yomybaby commented on react/src/components/StorageStatusPanel.tsx
> +            {maxVfolderCount && (
Please check this [thread](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1712209738006?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1712134401917&teamName=devops&channelName=Frontend&createdTime=1712209738006). Currently, the manager handles 0 as unlimited. It should be changed in the near future. But for now, let's display it as unlimited. @agatha197

2024-04-05 01:36 UTC, yomybaby requested changes
Please check [this](https://github.com/lablup/backend.ai-webui/pull/2292#discussion_r1552660658) out.

2024-04-05 01:52 UTC, agatha197 commented
> Please check [this](https://github.com/lablup/backend.ai-webui/pull/2292#discussion_r1552660658) out.
Updated!
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/6a6f5e3f-c94e-44e6-b77d-f5cb095282b7)

2024-04-05 03:08 UTC, yomybaby requested changes
<img width="499" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/2610f24a-7aad-46e6-a067-476ba6a3309a">

The count of created folders has to include virtual folders in the trash bin if the trash bin is supported, right? 

Also, the count doesn't change after creating and deleting permanently. It updates after refreshing the browser.

2024-04-05 05:08 UTC, agatha197 commented
> <img alt="image" width="499" src="https://private-user-images.githubusercontent.com/621215/319845438-2610f24a-7aad-46e6-a067-476ba6a3309a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTM5ODMsIm5iZiI6MTcxMjI5MzY4MywicGF0aCI6Ii82MjEyMTUvMzE5ODQ1NDM4LTI2MTBmMjRhLTdhYWQtNDZlNi1hMDY3LTQ3NmJhNmEzMzA5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwNTA4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTgzNTFiMzk5NTdlMDVlYzFjOTAyYWM0ZDI4MGMxY2VkZDhlNzBlZjFhNmU5ZTUyOTE4M2ZiNmRkMzY3NjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oPf_-vkLfOpjQpWsCTKJcmo4iFowNE1yo--AiWP5VGw">
> The count of created folders has to include virtual folders in the trash bin if the trash bin is supported, right?
> 
> Also, the count doesn't change after creating and deleting permanently. It updates after refreshing the browser.

handled in https://github.com/lablup/backend.ai-webui/pull/2302

2024-04-05 05:28 UTC, yomybaby approved these changes

2024-04-05 05:35 UTC, merged