feat: Introduce react-grid-layout for customizable summary page
lablup/backend.ai-webui pull request #2343
Opened 2024-04-16 05:04 UTC by ironAiken2

### This PR Resolves #2170 Issue.

### Feature
- [x] Apply a react grid layout with responsive support.
- [ ] Switch the components inside the item card to react.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-05-23 07:58 UTC, ironAiken2 commented
* **#2343** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2343?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-05 04:44 UTC, agatha197 requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/587491fe-3d80-4e38-8bf1-df151a78edd8.png)

The bottom is too narrow. Can you add more bottom padding?

2024-06-05 07:04 UTC, agatha197 approved these changes
LGTM

2024-06-20 05:23 UTC, yomybaby requested changes
@ironAiken2 please resolve conflicts.

2024-06-20 05:23 UTC, yomybaby commented on package.json
> +    "@types/react-grid-layout": "^1.3.5",
You don't need to add this type for web component parts.

2024-06-20 05:23 UTC, yomybaby commented on src/components/backend-ai-webui.ts
> -        </backend-ai-summary-view>
You also can delete this [part](https://github.com/lablup/backend.ai-webui/blob/065f3e2d88a0ccb4c86b12d62e9d4adf976fab8a/src/backend-ai-app.ts#L90-L93).

2024-06-20 08:27 UTC, ironAiken2 commented
> @ironAiken2 please resolve conflicts.

@yomybaby Conflict resolved.

2024-06-24 06:44 UTC, yomybaby approved these changes
LGTM

2024-06-24 06:46 UTC, merged