hotfix: only show vfolder when mount in session perm is allowed
lablup/backend.ai-webui pull request #2348
Opened 2024-04-16 14:55 UTC by lizable

This PR resolves the issue in Neo session launcher that shows vfolder list regardless of "`mount-in-session`" permission. For better user experience, we need to show vfolder which has proper permission unless It will throw error like this:

https://github.com/lablup/backend.ai-webui/assets/46954439/cfa97c2a-3253-4368-8ca2-a745063de041

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minimum required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-04-23 10:37 UTC, agatha197 requested changes

2024-04-23 10:37 UTC, agatha197 commented on react/src/components/VFolderTable.tsx
> +  );
```suggestion
  const allowedVFolderHostsByDomain = JSON.parse(domain?.allowed_vfolder_hosts || '{}');
  const allowedVFolderHostsByGroup = JSON.parse(group?.allowed_vfolder_hosts || '{}');
  const allowedVFolderHostsByKeypairResourcePolicy = JSON.parse(
    keypair_resource_policy?.allowed_vfolder_hosts || '{}',
  );
```
If `allowed_vfolder_hosts` is undefined, you can see this error.
<img width="561" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/67815450-2bf1-47c5-a57a-8dfc62799279">

2024-04-24 01:43 UTC, yomybaby requested changes

2024-04-24 01:43 UTC, yomybaby commented on react/src/components/VFolderTable.tsx
> +    .map((volume) => volume);
We can remove this. ` .map((volume) => volume);`

2024-04-24 05:06 UTC, agatha197 approved these changes
LGTM!

2024-04-24 07:53 UTC, yomybaby requested changes

2024-04-24 07:53 UTC, yomybaby commented on react/src/components/VFolderTable.tsx
> +  console.log(domain);
Please remove this

2024-04-24 07:53 UTC, yomybaby commented on react/src/components/VFolderTable.tsx
> +  console.log(domain);
```suggestion
```

2024-04-29 10:26 UTC, yomybaby commented
@lizable Please check a review and resolve conflicts. 😉

2024-04-30 02:48 UTC, yomybaby approved these changes
LGTM

2024-04-30 02:48 UTC, merged