fix: remove comments on config values
lablup/backend.ai-webui pull request #2383
Opened 2024-04-29 04:45 UTC by ironAiken2

### This PR Resolves #2382 Issue. (and minor fix on summary page's alert margin)

### Why the bug occurred
Inside the config.toml file, a description of each value is included as a comment. These comments were being read together to prevent the default value from being used even when no value was provided. 

### Feature
- Remove comments when reading config.toml values
- Adjust the alert margin at the top of the summary page

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-04-29 08:28 UTC, yomybaby requested changes

2024-04-29 08:28 UTC, yomybaby commented on react/src/components/AnnouncementAlert.tsx
> +        alignItems: 'center',
Please remove this. When the announcement has multiple lines, it's better to place a close button at the top instead of the middle.

2024-04-29 08:28 UTC, yomybaby commented on src/components/backend-ai-login.ts
> +        : '';
This is not a good idea because the value can have a #. 
```
some="This#Value#has#"
```

2024-04-29 08:28 UTC, yomybaby commented on src/components/backend-ai-login.ts
> +        : '';
If the current TOML parser does not support inline comments, please search for an alternative one that supports inline comments.

2024-05-13 09:08 UTC, ironAiken2 commented
* **#2383** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2383?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-19 07:42 UTC, closed without merging