feat: new resources page
lablup/backend.ai-webui pull request #2406
Opened 2024-05-07 10:05 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-05-08 07:24 UTC, agatha197 commented
* **#2406** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2406?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-09 03:56 UTC, yomybaby requested changes

2024-05-09 03:56 UTC, yomybaby commented on src/components/backend-ai-webui.ts
> -        </backend-ai-agent-view>
Also [import code](https://github.com/lablup/backend.ai-webui/blob/e872b63cb7d1708cede224a6dfcb7eb0b248779b/src/backend-ai-app.ts#L124-L127) is not necessary anymore, right?

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/MainLayout/WebUISider.tsx
> +          // @ts-ignore
Is this required?

2024-05-09 03:56 UTC, yomybaby commented on react/src/pages/ResourcesPage.tsx
> +      {curTabKey === 'storages' ? (
When you change the tab, the page options should be reset because the list has a different total size.

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +      },
```suggestion
        return index + 1 + (paginationStates.page - 1) * paginationStates.pageSize;
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +            <img
```suggestion
          <Flex gap={'xxs'}>
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +      },
Without gap: <img width="102" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/566a6553-bebb-4d86-9ba5-dd044f90b73c">

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +        (a?.architecture ?? '').localeCompare(b?.architecture ?? ''),
Let's add the following function to `/helper/index.ts` and use it in the same way as the Control panel.
```
export const localeCompare = (a?: string | null, b?: string | null) => {
  if (a === null || a === undefined) return -1;
  if (b === null || b === undefined) return 1;
  return a.localeCompare(b);
};
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +            </Typography.Text>
For the storage, please do not use iSizeToSize. iSizeToSize is for `iB` size.

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +                  <Tag color="blue">Fractional GPU™</Tag>
This is typo, right?
```suggestion
                {_.includes(_.keys(parsedAvailableSlots), 'cuda.shares') ? (
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentDetailModal.tsx
> +          ) {
```suggestion
            ['cpu_util', 'mem', 'disk', 'net_rx', 'net_tx'].includes(key)
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentDetailModal.tsx
> +    >
FYI, this is another way to display only one button.
```suggestion
      cancelButtonProps={{style:{display:'none'}}}
      onOk={onRequestClose}
      okText={t('button.Close')}
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentDetailModal.tsx
> +      onCancel={onRequestClose}
How about add a id(name) to the modal title.
```suggestion
      title={`${t('agent.DetailedInformation')}: ${agent?.id}`}
```

2024-05-09 03:56 UTC, yomybaby commented on react/src/components/AgentSettingModal.tsx
> +      onCancel={() => onRequestClose()}
Here also.

2024-05-09 08:21 UTC, agatha197 commented on react/src/components/MainLayout/WebUISider.tsx
> +          // @ts-ignore
I got `'menu' is of type 'unknown'` error. So I added type definitions.

2024-05-10 06:26 UTC, yomybaby commented on react/src/components/AgentList.tsx
> +            ) {
Fix condition:
```suggestion
            if (
              _.isNumber(current) &&
              _.isNumber(pageSize) &&
              (pageSize !== tablePaginationOption.pageSize ||
                current !== tablePaginationOption.current)
            ) {
```

2024-05-13 01:34 UTC, yomybaby approved these changes
LGTM

2024-05-13 01:38 UTC, merged