fix: align button consistency on Resource Group pages
lablup/backend.ai-webui pull request #2436
Opened 2024-05-27 12:06 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-05-27 12:06 UTC, ironAiken2 commented
* **#2436** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2436?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-28 04:39 UTC, agatha197 requested changes
<img width="367" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/0c5876b0-6b8e-42b2-a872-6feb0d71231b">
<img width="370" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/ce1032df-0dc1-4dfe-a073-a9006c686479">

This PR reduces the width of the bottom button in the Create/Modify Resource Group dialog. Please modify it again so it doesn't affect this.

2024-05-28 04:43 UTC, yomybaby reviewed
I push one commit to improve UX. please check the commit.

2024-05-28 05:11 UTC, ironAiken2 commented
Applied @agatha197 

> <img width="367" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/0c5876b0-6b8e-42b2-a872-6feb0d71231b">
> <img width="370" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/ce1032df-0dc1-4dfe-a073-a9006c686479">
> 
> ~~This PR reduces the width of the bottom button in the Create/Modify Resource Group dialog. Please modify it again so it doesn't affect this.~~
> For consistency, please widen the bottom button in the Create/Modify Resource Group dialog too.
>  You can use [`full`](https://github.com/lablup/backend.ai-webui/blob/main/src/components/backend-ai-general-styles.ts#L994-L995) class for this.
> 
>

2024-05-28 07:06 UTC, yomybaby requested changes

2024-05-28 07:06 UTC, yomybaby commented on src/components/backend-ai-session-list.ts
> +    this.requestUpdate();
I thik that this is not related to this PR? Please remove this

2024-05-28 07:28 UTC, yomybaby approved these changes
LGTM

2024-05-28 07:32 UTC, merged