feat: memorize board's items by using local storage
lablup/backend.ai-webui pull request #2441
Opened 2024-05-29 07:49 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-05-29 07:49 UTC, ironAiken2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2441?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2441** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2441?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2343** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2343?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-05 07:22 UTC, agatha197 requested changes

2024-06-05 07:22 UTC, agatha197 commented on react/src/pages/SummaryPage.tsx
> +}
```suggestion
}
type StringifyItem = {
  id: string;
  rowSpan: number;
  columnSpan: number;
  data: {
    title: string;
    content: string;
  };
};
```

2024-06-05 07:22 UTC, agatha197 commented on react/src/pages/SummaryPage.tsx
> +    'backendaiwebui.board_items.summary',
```suggestion
 const [stringifyItems, setStringifyItems] = useLocalStorageState<
    StringifyItem[]
  >('backendaiwebui.board_items.summary',
```

2024-06-05 07:22 UTC, agatha197 commented on react/src/pages/SummaryPage.tsx
> +    return stringifyItems?.map((item) => ({
```suggestion
    return _.map(boardItems, (item) => ({
```

2024-06-05 07:22 UTC, agatha197 commented on react/src/pages/SummaryPage.tsx
> +    setStringifyItems(stringifiedItems as any);
```suggestion
    setStringifyItems(stringifiedItems as StringifyItem[]);
```

2024-06-24 04:10 UTC, lizable requested changes
Is the purpose of using local storage is to store the order of displaying items of summary pages? If so, we shall use "useBAISetting" component instead of using localStorage. Here's the good example code for that. We need a little modification, though.

https://github.com/lablup/backend.ai-webui/blob/a3638bfc5c9f369d7c772b19002e80a19ec6306b/react/src/components/MainLayout/MainLayout.tsx#L41

2024-06-25 08:46 UTC, yomybaby approved these changes
I have pushed a commit. Please review the commit and merge it if ok. @ironAiken2

2024-06-25 08:46 UTC, yomybaby commented on react/src/pages/SummaryPage.tsx
> +    startMenu: {
```suggestion
  const defaultSummaryElements = {
```

2024-06-25 09:31 UTC, lizable approved these changes
LGTM.

2024-06-26 04:54 UTC, agatha197 approved these changes
LGTM!

2024-06-26 04:56 UTC, merged