feat: apply `SettingList` component into user setting page
lablup/backend.ai-webui pull request #2465
Opened 2024-06-07 06:36 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-06-07 06:37 UTC, ironAiken2 commented
* **#2465** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2465?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-10 09:20 UTC, yomybaby requested changes
I haven't finished the review yet, but I'd like to leave some feedback first.

2024-06-10 09:20 UTC, yomybaby commented on react/src/components/SettingList.tsx
>        </Flex>
Please add a confirm popup for this feature.

2024-06-10 09:20 UTC, yomybaby commented on react/src/components/SettingList.tsx
> +        items={_.map(appendedAllSettingGroup, (settingGroup) => {
How about always adding `filterItems.length`? 
Please use secondary text for count.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/9ab44b95-675b-4de9-81fd-3afd8dbfc47b.png)

2024-06-24 07:51 UTC, yomybaby approved these changes
LGTM

2024-06-24 07:55 UTC, merged