feat: Import notebook using Neo Session Launcher
lablup/backend.ai-webui pull request #2466
Opened 2024-06-10 03:35 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-06-10 03:35 UTC, yomybaby commented
* **#2466** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2466?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-09 07:43 UTC, agatha197 requested changes

2024-07-09 07:43 UTC, agatha197 commented on react/src/components/LocationStateBreadCrumb.tsx
> +    locationState.from && (
```suggestion
    locationState?.from && (
```
From can be null. I got this error from here.
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/fae9702c-2089-445e-b8d8-dcaa6a6bf928.png)

2024-07-09 07:43 UTC, agatha197 commented on react/src/components/LocationStateBreadCrumb.tsx
> +            title: locationState.from.label || locationState.from.pathname,
```suggestion
            title: locationState.from?.label || locationState.from?.pathname,
```

2024-07-09 07:43 UTC, agatha197 commented on react/src/components/LocationStateBreadCrumb.tsx
> +            href: locationState.from.pathname,
```suggestion
            href: locationState.from?.pathname,
```

2024-07-11 05:27 UTC, agatha197 approved these changes
LGTM

2024-07-11 05:30 UTC, merged