feat: vFolder explorer permerlink
lablup/backend.ai-webui pull request #2476
Opened 2024-06-13 10:20 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-06-13 10:21 UTC, yomybaby commented
* **#2476** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2476?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-17 01:36 UTC, agatha197 requested changes
Sometimes it doesn't work after a few refreshes.

2024-06-18 07:56 UTC, yomybaby commented
@agatha197 I fixed that bug. Please check it again

2024-06-18 10:21 UTC, agatha197 approved these changes
LGTM!

2024-06-18 10:22 UTC, merged