bug: set dark theme color for error panel in session detail modal
lablup/backend.ai-webui pull request #2489
Opened 2024-06-21 03:12 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-06-21 03:13 UTC, ironAiken2 commented
* **#2489** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2489?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-21 15:13 UTC, agatha197 requested changes

2024-06-21 15:13 UTC, agatha197 commented on src/components/backend-ai-session-list.ts
> +          border-radius: 4px;
```suggestion
          border-radius: var(--token-borderRadiusSM, 4px);
```

2024-06-21 15:13 UTC, agatha197 commented on src/components/backend-ai-session-list.ts
> +          margin: 10px;
```suggestion
          padding: var(--token-paddingSM, 10px);
          margin: var(--token-marginSM, 10px);
```

2024-06-24 07:00 UTC, agatha197 approved these changes
LGTM

2024-06-24 07:03 UTC, merged