feature: Not connected alert banner in React
lablup/backend.ai-webui pull request #2492
Opened 2024-06-25 05:55 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-06-25 05:55 UTC, yomybaby commented
* **#2493** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2493?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2492** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2492?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-25 07:59 UTC, yomybaby commented on react/src/components/NetworkStatusBanner.tsx
> +  const [softTimeout, setSoftTimeout] = useAtom(networkSoftTimeoutAtom);
FYI, `softTimeot` feature is handled by #2493 .

2024-06-26 05:38 UTC, ironAiken2 requested changes
After the network is reconnected, the notifiaction will output a network shutdown statement. How about removing that wording, or modifying it to appear at the same time as the banner?

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/7e24ce77-2c3b-41ea-9198-46ec53d87afc.png)

2024-07-01 00:25 UTC, yomybaby commented
@ironAiken2 I created a new stack to improve notifications. Please check that #2502 PR and resolve a current PR.

2024-07-01 02:33 UTC, ironAiken2 approved these changes
LGTM!

2024-07-01 02:36 UTC, merged