feat: introduce exporting CSV module
lablup/backend.ai-webui pull request #2513
Opened 2024-07-04 01:59 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-04 01:59 UTC, ironAiken2 commented
* **#2513** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2513?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-09 02:56 UTC, agatha197 requested changes
<img width="891" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/6f2fb818-1df7-46c7-9123-5a54cac4fba9">
I got strange data from the keypair list. please check again :)

2024-07-09 03:03 UTC, agatha197 requested changes
I found missing i18n and debug codes.

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/KeypairResourcePolicyList.tsx
> +                  label: 'Export CSV',
Please use i18n

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/KeypairResourcePolicyList.tsx
> +                Tools
Same as above.

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/ProjectResourcePolicyList.tsx
> +  console.log(project_resource_policies);
```suggestion
```

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/ProjectResourcePolicyList.tsx
> +                  label: 'Export CSV',
Same as above.

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/ProjectResourcePolicyList.tsx
> +                Tools
Same as above.

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/UserResourcePolicyList.tsx
> +  console.log('#!@#: ', user_resource_policies);
```suggestion
```

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/UserResourcePolicyList.tsx
> +                  label: 'Export CSV',
Same as above.

2024-07-09 03:03 UTC, agatha197 commented on react/src/components/UserResourcePolicyList.tsx
> +                Tools
Same as above.

2024-07-09 04:11 UTC, yomybaby requested changes
How about introducing these functions to generate a CSV like the following:

```
// User type
type User = {
  id: number;
  name: string;
  email: string;
  registeredAt: Date;
};

// Example
const users: Array<User> = [
  { id: 1, name: 'John Doe', email: 'john@example.com', registeredAt: new Date('2020-01-01') },
  { id: 2, name: 'Jane Doe', email: 'jane@example.com', registeredAt: new Date('2020-02-01') }
];

// Example usage of the dataToCSV function
const str = dataToCSVString(users, {
  id: 'User ID', // Directly provide a string for the label
  name: { label: 'Full Name', format: value => value.toUpperCase() }, // Convert name to uppercase
  email: 'Email Address', // Only specify the label, no format change
  registeredAt: { // Format the date as 'yyyy-MM-dd'
    label: 'Registration Date',
    format: (value: Date) => `${value.getFullYear()}-${value.getMonth() + 1}-${value.getDate()}`
  }
});

downloadAsCSVFile = (str) = > downloadFile(new Blob([str], {type:'text/csv'})
```

2024-07-26 05:06 UTC, agatha197 requested changes

2024-07-26 05:06 UTC, agatha197 commented on react/src/components/KeypairResourcePolicyList.tsx
> +        allowed_vfolder_hosts: (text) => _.keys(JSON.parse(text)).join(', '),
how about displaying `-` if `allowed_vfolder_hosts` is empty?

2024-07-26 05:06 UTC, agatha197 commented on react/src/components/ProjectResourcePolicyList.tsx
> +        created_at: (text) => dayjs(text).format('lll'),
we don't need to format the time in csv :)

2024-07-26 05:06 UTC, agatha197 commented on react/src/components/UserResourcePolicyList.tsx
> +        created_at: (text) => dayjs(text).format('lll'),
same as above.

2024-07-29 05:26 UTC, agatha197 requested changes
It would be better to put the logic to display empty values as `-` inside the `exportCSVWithFormattingRules` function.

2024-07-29 08:11 UTC, ironAiken2 commented
Since the empty value has different rules for indicating empty for each field (e.g., the _.isEmpty function treats the number 0 or '', {} as empty), we decided to keep the existing structure so that we can set rules for each field.

2024-07-29 08:59 UTC, agatha197 commented
> Since the empty value has different rules for indicating empty for each field (e.g., the _.isEmpty function treats the number 0 or '', {} as empty), we decided to keep the existing structure so that we can set rules for each field.

I initially thought of using _.isEmpty as the default and overriding it with other empty detection functions when needed. However, as you pointed out, this could lead to unintended situations such as treating the number 0 as empty. Let's keep it as it is then.

2024-07-29 09:03 UTC, agatha197 requested changes

2024-07-29 09:03 UTC, agatha197 commented on react/src/components/KeypairResourcePolicyList.tsx
> +          _.isEmpty(text) ? JSON.stringify(text) : '-',
```suggestion
          _.isEmpty(text) ?  '-' : JSON.stringify(text),
```

2024-07-30 02:16 UTC, agatha197 approved these changes
LGTM 👊

2024-08-06 04:59 UTC, lizable approved these changes
LGTM.

2024-08-06 05:02 UTC, merged