Add an 'Import from hugging face' modal
lablup/backend.ai-webui pull request #2514
Opened 2024-07-04 07:16 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-04 07:16 UTC, agatha197 commented
* **#2514** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-05 02:37 UTC, yomybaby approved these changes
LGTM, but it's better to merge later after finishing upcomming stacks for integrating the API.

2024-09-20 03:32 UTC, yomybaby requested changes

2024-09-20 03:32 UTC, yomybaby commented on react/src/hooks/backendai.tsx
> +    [key: string]: ResourceSlotDetail;
Please check this change. It seems like an unintended change.

2024-09-20 03:59 UTC, yomybaby approved these changes
LGTM

2024-09-20 04:01 UTC, merged