feat: use pnpm instead of npm
lablup/backend.ai-webui pull request #2515
Opened 2024-07-04 07:25 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-04 07:25 UTC, yomybaby commented
* **#2515** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2515?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-12 05:21 UTC, Yaminyam commented on .gitignore
It would be a good idea to also add `pnpm-debug.log`.

2024-07-12 10:32 UTC, lizable requested changes
I got error "Cannot find module node:events" while building desktop app.

![Screenshot 2024-07-12 at 7.31.13 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/e5b00177-14db-45ff-9856-30491b31d2fc.png)

2024-07-12 10:43 UTC, lizable reviewed
Tested whether feature works properly using pnpm and it works fine.
Also building desktop app using `Makefile` is also works without error.
It would be good to go after applying @Yaminyam 's suggestion, though.

2024-07-15 23:31 UTC, yomybaby commented on .gitignore
Done.
```
pnpm-debug.log*
pnpm-error.log*
```

2024-07-16 02:06 UTC, lizable approved these changes
LGTM.

2024-07-16 02:08 UTC, merged

2024-07-16 02:09 UTC, Yaminyam reviewed
It would be a good idea to add the contents added to `.gitignore` to `.dockerignore` as well.