feat: add a checkbox to select all items in session list
lablup/backend.ai-webui pull request #2519
Opened 2024-07-05 09:51 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-05 09:51 UTC, ironAiken2 commented
* **#2519** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2519?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-08 14:22 UTC, agatha197 requested changes
Is it possible to make the header checkbox checked when all items are selected, and unchecked when all items are unchecked? Or you can use just vaadin selection column. ref: https://vaadin.com/docs/latest/components/grid#selection

2024-07-08 14:22 UTC, agatha197 commented on src/components/backend-ai-session-list.ts
> +    console.log(this._selected_items);
```suggestion
```

2024-07-09 01:48 UTC, ironAiken2 commented
It was already built into vaadin library... why didn't I find it? I'll look into it and incorporate it. Thank you for your review @agatha197

2024-07-22 04:02 UTC, yomybaby requested changes
I found a bug. After a few seconds of selecting a session, the checkbox automatically changes to unchecked. Please check it.

2024-07-24 07:25 UTC, agatha197 requested changes
LGTM But please reflect one feedback :)

2024-07-24 07:25 UTC, agatha197 commented on src/components/backend-ai-session-list.ts
> +            this._isRunning || this._APIMajorVersion > 4
```suggestion
            this._isRunning
```
This code adds a selection column to the terminated session tabs. Let's remove it.

2024-07-29 04:35 UTC, yomybaby commented
LGTM!

2024-07-29 04:36 UTC, yomybaby approved these changes

2024-07-29 05:17 UTC, agatha197 approved these changes
LGTM

2024-07-29 05:20 UTC, merged