add: existing environment when modifying endpoint or querying endpoint detail
lablup/backend.ai-webui pull request #2525
Opened 2024-07-08 08:17 UTC by lizable

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-08 08:17 UTC, lizable commented
* **#2525** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2525?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lizable and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-08 14:15 UTC, agatha197 requested changes

2024-07-08 14:15 UTC, agatha197 commented on react/src/components/ServiceLauncherPageContent.tsx
> +        ),
```suggestion
        envvars: _.map(
          JSON.parse(endpoint?.environ || '{}'),
          (value, variable) => ({ variable, value }),
        ),
```

2024-07-08 14:15 UTC, agatha197 commented on react/src/pages/EndpointDetailPage.tsx
> +        {_.isEmpty(JSON.parse(endpoint?.environ)) ? 'None' : endpoint?.environ}
```suggestion
        {_.isEmpty(JSON.parse(endpoint?.environ)) ? '-' : endpoint?.environ}
```

2024-07-10 05:18 UTC, agatha197 approved these changes
LGTM

2024-07-10 05:21 UTC, merged