feat: introduce regacy folder explorer for calling explorer at anywhere
lablup/backend.ai-webui pull request #2529
Opened 2024-07-09 09:50 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-09 09:50 UTC, ironAiken2 commented
* **#2529** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2529?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-10 00:34 UTC, rapsealk commented
Please check for the title! 😉

2024-07-16 03:46 UTC, yomybaby requested changes
Please check below:
- In the existing version, the delete button at the top appears when the user selects files.
    ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/b79c5c57-2a9f-4981-b37e-dd06a4d960d5.png)
- When the explorer is closed, the selected tab in the query string is deleted.


<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/XqC2uNFuj0wg8I60sMUh/b89e4e27-df48-44b1-8a15-428a8d6cf1e2.mp4">
              <img src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/XqC2uNFuj0wg8I60sMUh/b89e4e27-df48-44b1-8a15-428a8d6cf1e2.mp4">
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/b89e4e27-df48-44b1-8a15-428a8d6cf1e2.mp4">iShot_2024-07-16_12.44.42.mp4</video>

2024-07-16 04:08 UTC, yomybaby requested changes

2024-07-16 04:08 UTC, yomybaby commented on src/components/backend-ai-data-view.ts
> +    console.log('Event: ', e);
Please delete this

2024-07-16 04:08 UTC, yomybaby commented on src/components/backend-ai-storage-list.ts
Please delete the code related to the folder explorer that is not currently being used.

2024-07-16 04:08 UTC, yomybaby commented on src/components/backend-ai-storage-list.ts
And please check the changes in these files. It looks like there is a mistake.

2024-07-19 01:10 UTC, ironAiken2 commented on src/components/backend-ai-storage-list.ts
I don't know why this file got a modification.... I've restored it to its original state.

2024-07-19 05:05 UTC, ironAiken2 commented
All requests have been applied. @yomybaby

2024-07-25 05:39 UTC, agatha197 requested changes
1. The previous folder name remained after creating/renaming a new sub folder(create inside the folder explorer).
2. I cannot delete subfolders
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/a70d072d-6c2c-49b0-939e-ee1f96a24a04.png)
3. I cannot download any files.
4. When uploading a folder, it overwrites regardless of case sensitivity. For example, if you create a folder named 'a' in the file explorer and upload a folder named 'A', the files inside the 'A' folder will be placed inside the 'a' folder.
5. When I renamed a file, I got this error from storage proxy.
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/6f28013b-bf4e-4793-9f06-7a235f864adf.png)
6. The download icon is sometimes inactive even though the permission is enabled.

2024-07-26 05:11 UTC, ironAiken2 commented
2. I cannot delete subfolders 
-> Fixed.  The issue was caused by not being able to read the filename.

2024-07-31 02:09 UTC, agatha197 requested changes
1. It would be better to show this modal if user try to modify extension.
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/6e7f71d4-7b4d-4b2e-aa8c-12546f6bb72b.png)
2. And the bottom buttons of upper confirm modal doesn't have `gap`.
3. The right bottom button string is too long.

2024-07-31 02:09 UTC, agatha197 commented on src/components/backend-ai-folder-explorer.ts
> +          /^([^`~!@#$%^&*()|+=?;:'",<>{}[\]\r\n/]{1,})+(\/[^`~!@#$%^&*()|+=?;:'",<>{}[\]\r\n/]{1,})*([/,\\]{0,1})$/gm;
suggest: ```^[^`~!@#$%^&*()|+=?;:'",<>{}[\]\r\n/]+(\/[^`~!@#$%^&*()|+=?;:'",<>{}[\]\r\n/]+)*[\/\\]?$```

2024-07-31 05:03 UTC, agatha197 requested changes
Let's add `destroyOnClose` to rename modal.

2024-07-31 05:33 UTC, ironAiken2 commented
> Let's add destroyOnClose to rename modal.

Since the modal is written as a web component, I modified it to set empty the field when the modal opens.
@agatha197

2024-07-31 08:55 UTC, agatha197 approved these changes
LGTM!

2024-08-05 08:00 UTC, yomybaby requested changes

2024-08-05 08:00 UTC, yomybaby commented on react/src/components/FolderExplorerOpener.tsx
> +          setVFolderName(vFolder?.name || '');
```suggestion
          setVFolderName(vFolder?.name || '');
```

2024-08-05 08:00 UTC, yomybaby commented on react/src/components/BAIModal.tsx
> +        className={`bai-modal ${className ?? ''}`}
Next time, let's consider using https://github.com/JedWatson/classnames.

2024-08-12 07:49 UTC, yomybaby approved these changes
🙌 LGTM with #2622. Don't merge without #2622 .

2024-08-12 07:51 UTC, merged