refactor: TimeContainer for counting down valid login session time
lablup/backend.ai-webui pull request #2551
Opened 2024-07-16 09:42 UTC by lizable

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-16 09:42 UTC, lizable commented
* **#2551** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2551?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lizable and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-29 01:26 UTC, agatha197 requested changes
Please check the [test](https://github.com/lablup/backend.ai-webui/actions/runs/10110244267/job/27959772213?pr=2551)

2024-07-29 01:26 UTC, agatha197 commented on react/src/components/TimeContainer.tsx
> +      setExpires((prevExpires) => prevExpires - 1); // 1초씩 감소
```suggestion
      setExpires((prevExpires) => prevExpires - 1); // Decrease by 1 second each time.
```

2024-07-29 09:41 UTC, agatha197 requested changes
When set to 15 seconds, extending it results in 14 seconds (which is correct), but refreshing extends it to 13 seconds. Both should be extended to 14 seconds.

2024-07-30 03:58 UTC, yomybaby requested changes

2024-07-30 03:58 UTC, yomybaby commented on react/src/components/TimeContainer.tsx
> +        delay={1000}
To display more accurate time:
```suggestion
        delay={100}
```

2024-08-05 07:56 UTC, yomybaby requested changes

2024-08-05 07:56 UTC, yomybaby commented on react/src/components/TimeContainer.tsx
>    });
```suggestion
  const { data } = useSuspenseQuery<{
    expires: string;
  }>({
    queryKey: ['TimeContainerExpires'],
    queryFn: () => {
      return baiRequestWithPromise({
        method: 'POST',
        url: `/server/extend-login-session`,
      });
    },
    staleTime: 0,
    cacheTime: 0,
    fetchKey
  });
```

2024-08-05 07:56 UTC, yomybaby commented on react/src/components/TimeContainer.tsx
> +const TimeContainer: React.FC<TimeContainerProps> = ({
It's better to use a more explicit name. `TimeContainer` => `LoginSessionExtendButton`

2024-09-02 05:08 UTC, yomybaby approved these changes
LGTM

2024-09-02 09:06 UTC, agatha197 requested changes

2024-09-02 09:06 UTC, agatha197 commented on config.toml.sample
> +enableExtendLoginSession = false        # If true, enables login session extension UI. (From Backend.AI 24.03.7)
```suggestion
enableExtendLoginSession = false        # If true, enables login session extension UI. (From Backend.AI 24.09)
```

2024-09-02 09:11 UTC, agatha197 approved these changes
LGTM!

2024-09-02 09:13 UTC, merged