feat: remove password validation for superadmin
lablup/backend.ai-webui pull request #2561
Opened 2024-07-18 07:47 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-18 07:47 UTC, agatha197 commented
* **#2561** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2561?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-18 07:52 UTC, yomybaby requested changes
Could you please provide the link to the Teams thread or GitBox link if it exists?

2024-07-18 08:11 UTC, agatha197 commented
> Could you please provide the link to the Teams thread or GitBox link if it exists?

[Teams Thread](https://teams.microsoft.com/l/message/19:56185f8ff32e4393bff26c11ce37a5d1@thread.tacv2/1721286301681?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1720660078308&teamName=customers%20%26%20clients&channelName=NHNCloud-AICA&createdTime=1721286301681)

2024-07-19 00:26 UTC, yomybaby requested changes
I followed the description in https://github.com/lablup/backend.ai/pull/1284 to set `max_password_age`. But I can see the `ResetPasswordRequired` modal even though the response of the `/login` page is as below:
```
{
    "authenticated": false,
    "data": {
        "type": "https://api.backend.ai/probs/password-expired",
        "title": "Password has expired.",
        "details": "Password expired on 2024-04-17 08:45:02.388511+00:00."
    }
}
```

2024-07-29 04:27 UTC, yomybaby approved these changes
LGTM

2024-07-29 04:31 UTC, merged