fix: resource icon and unit are not displayed on KeypairResourcePolicyList
lablup/backend.ai-webui pull request #2566
Opened 2024-07-22 03:33 UTC by gahyuun

### TL;DR

fix error that resource icon and unit are not displayed on KeyPairResourcePolicyList

### What changed?

Added `isImportingDeviceMetaData` in `ResourceNumber.tsx`. `isImportingDeviceMetaData` determines whether to import device meta data
Modified  `KeyPairResourcePolicyList` to pass true to `isImportingDeviceMetaData` prop 

Importing deviceMetaData directly into the `KeyPairResourcePolicyList `was not implemented in that way due to duplication and flow of data

2024-07-22 03:57 UTC, yomybaby requested changes
Please append links to the description, such as an issue or a team thread related to this PR.

2024-07-22 04:05 UTC, gahyuun commented
> Please append links to the description, such as an issue or a team thread related to this PR.

I modified it!

2024-07-23 02:19 UTC, yomybaby requested changes
For React props, using nouns is more suitable most of cases. It becomes shorter and more concise. For example, `loding` is better than `isLoading` as a prop.

It's better to resolve this issue without adding new props. Let's merge `resourceSlots and `deviceMetadata` in  [this line](https://github.com/lablup/backend.ai-webui/blob/5a7bace32580b50f08cc81fe30ff6c1ef7e89fe8/react/src/hooks/backendai.tsx#L106-L107) using _.merge

2024-07-23 04:14 UTC, gahyuun commented
> For React props, using nouns is more suitable most of cases. It becomes shorter and more concise. For example, `loding` is better than `isLoading` as a prop.
> 
> It's better to resolve this issue without adding new props. Let's merge `resourceSlots and `deviceMetadata` in [this line](https://github.com/lablup/backend.ai-webui/blob/5a7bace32580b50f08cc81fe30ff6c1ef7e89fe8/react/src/hooks/backendai.tsx#L106-L107) using _.merge

I modified it ! thanks for reviewing

I agree using nouns is shorter and more concise but I think that `IsLoading` is more intuitive and semantically clear than `loading` when it has a boolean value. What do you think about this?

2024-07-29 04:27 UTC, yomybaby approved these changes
LGTM

2024-07-29 04:29 UTC, merged