chore: update react-query
lablup/backend.ai-webui pull request #2591
Opened 2024-07-31 05:09 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-07-31 05:09 UTC, yomybaby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2591?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2591** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2591?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2590** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2590?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-31 07:57 UTC, yomybaby commented on react/src/components/ResourceGroupSelect.tsx
>    });
This is a use case for `fetchKey` instead of updating `queryKey`.

2024-08-02 03:00 UTC, agatha197 requested changes
I got this error when creating a new session. Can you check it?
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/b41ecbac-1ecc-407d-9c1c-353c7ac5a610.png)

2024-08-05 03:21 UTC, agatha197 requested changes
Please resolve the conflicts.

2024-08-09 04:19 UTC, yomybaby commented
I resolve that error. Please check again.

2024-08-09 08:19 UTC, ironAiken2 approved these changes
LGTM!

(I tested for no build errors, good handling with suspense fallback, and refetching on fetchkey updates).

2024-08-09 09:50 UTC, merged