add: AgentSelect when hideAgent configuration is disabled
lablup/backend.ai-webui pull request #2599
Opened 2024-08-01 09:09 UTC by lizable

Resolves #2589 

**Changes:**
Adds agent selection capability to the session launcher, allowing users to manually choose specific compute agents instead of relying solely on automatic scheduler allocation.

Key additions:
- New `AgentSelect` component displaying available agents with their remaining resource capacities
- Integration into resource allocation form with auto-select option as default
- Agent selection is restricted to single-node single-container environments
- Added translations for agent selection UI elements across multiple languages

When a specific agent is selected:
- Cluster mode is forced to single-node
- Cluster size is set to 1
- The selection is passed to the backend via the `agent_list` parameter

The agent selector includes a refresh button to update the available agent list and displays real-time resource availability for each agent.

**Minimum requirements to check:**
- Agent selection dropdown shows available agents with correct resource information
- Selecting a specific agent properly restricts cluster configuration
- Auto-select option works as default
- Refresh button updates the agent list
- Agent selection is only available when not hidden by configuration

**Test cases:**
> ⚠️ Prerequisites:
> 1. Set the value of  `hideAgents` in config file to false.
> 2. Change the branch of Backend.AI Core to this PR (https://app.graphite.dev/github/pr/lablup/backend.ai/2614/refactor-apply-session-allocation-at-specific-agent-when-hide-agent-option-is-disabled)
> 3. Set the value of `hide-agents` to false in manager.toml file
> 4. Restart Manager process. 

1. Verify agent list displays with resource information
2. Confirm cluster settings are restricted when specific agent is selected
3. Test refresh functionality updates available agents
4. Validate auto-select behavior works as expected

### Screenshot(s)
| After | Before |
|------|--------|
| ![Screenshot 2024-11-05 at 6.23.47 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/a7a8c6ff-1ba2-4efd-a713-8f33df11c084.png) | ![Screenshot 2024-11-05 at 6.24.18 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/37e308b0-0463-4959-a455-0701f6cc9a9a.png) |

2024-08-01 09:09 UTC, lizable commented
* **#2599** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lizable and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-06 04:31 UTC, yomybaby requested changes
🙏  Please resolve conflicts. @lizable

2024-11-06 04:32 UTC, agatha197 requested changes
Please resolve the conflicts :)

2024-11-06 04:32 UTC, agatha197 commented on react/src/components/AgentSelect.tsx
> +  console.log(agentOptions);
```suggestion
```

2024-11-07 02:24 UTC, yomybaby requested changes
> "Currently, agent selection is only available in a single-node single-container environment." 

~~It's better to disable and change the form values related to cluster setting when user set the specific agent.~~Oh, I see you've already handled this. I'll check again when the multi-node test server is ready.

2024-11-07 02:24 UTC, yomybaby commented on react/src/components/AgentSelect.tsx
> +const AgentSelector: React.FC<Props> = ({
Please rename to "AgentSelect" 😀

2024-11-08 04:16 UTC, yomybaby requested changes
Additional work to be necessary:
- Add agent info to preview step
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/a9733d86-19ee-4024-a83c-3553441cd037.png)
- Please add a version condition to ensure version compatibility.

Below is not related to this PR's changes, but need to be fix
- When pending status, "null(undefined)" in Agent column
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/0cfe296e-c830-4dba-b177-7cdf38dbcb7d.png)

2024-11-08 10:14 UTC, yomybaby approved these changes
LGTM 💪

2024-11-11 02:14 UTC, agatha197 requested changes
AgentSelector still remains.

2024-11-11 02:14 UTC, agatha197 commented on react/src/components/ResourceAllocationFormItems.tsx
> +import AgentSelector from './AgentSelect';
```suggestion
import AgentSelect from './AgentSelect';
```

2024-11-11 02:14 UTC, agatha197 commented on react/src/components/ResourceAllocationFormItems.tsx
> +              <AgentSelector
```suggestion
              <AgentSelect
```

2024-11-11 02:14 UTC, agatha197 commented on react/src/components/ResourceAllocationFormItems.tsx
> +              ></AgentSelector>
```suggestion
              />
```

2024-11-11 03:01 UTC, agatha197 approved these changes
Let's handle the resource preset issue separately. LGTM

2024-11-11 03:05 UTC, merged