feat: add confirm dialog before moving to trash bin tab
lablup/backend.ai-webui pull request #2610
Opened 2024-08-06 15:28 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-06 15:28 UTC, agatha197 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2610?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2610** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2610?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2609** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2609?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-07 01:39 UTC, ironAiken2 requested changes
It's very minor, but it would be nice to use quotation marks ("") in folder names to make it clearer. :)

2024-08-07 01:47 UTC, agatha197 commented
> It's very minor, but it would be nice to use quotation marks ("") in folder names to make it clearer. :)

Done!

2024-08-07 01:49 UTC, ironAiken2 approved these changes
LGTM!

2024-08-07 02:00 UTC, merged