feat: update packages
lablup/backend.ai-webui pull request #2611
Opened 2024-08-06 15:49 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-08 08:24 UTC, yomybaby requested changes
Please also update `/react/package.json`.

2024-08-08 08:34 UTC, agatha197 commented
> Please also update `/react/package.json`.

Done!

2024-08-09 04:51 UTC, yomybaby commented on react/src/components/lablupTalkativotUI/LLMChatCard.tsx
> +        messages={messages as Array<Message>}
You don't neet to use `as`. I'll push a commit to remove `as`

2024-08-09 05:54 UTC, yomybaby approved these changes
LGTM

2024-08-09 07:43 UTC, merged