feat: add support for Gaudi 2 Accelerator
lablup/backend.ai-webui pull request #2623
Opened 2024-08-09 14:19 UTC by kyujin-cho

This PR adds support for dealing with Gaudi 2 accelerator from WebUI.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-12 09:15 UTC, agatha197 commented
* **#2623** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2623?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kyujin-cho and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 03:07 UTC, yomybaby requested changes

2024-09-03 03:07 UTC, yomybaby commented on react/src/helper/index.tsx
> +  if (sizeIndex === -1 || isNaN(sizeValue) || !sizeValue) {
@agatha197, Can I ask why did you add the `!sizeValue` condition? This causes an error when `iSizeToSize("0g","b");` is called.

2024-09-03 03:25 UTC, yomybaby reviewed
After this PR, the Resource Number is displayed with the `~∞` even where it is not needed.
<img width="724" alt="image" src="https://github.com/user-attachments/assets/c8f54f19-e2a6-45b5-b8e6-8b7152c13299">

2024-09-03 07:32 UTC, ironAiken2 requested changes
If you run a session with accelerator set to 1 or higher, the session list does not reflect the accelerator.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/e9925eda-3306-4971-b460-3421ea58e022.png)

2024-09-03 09:30 UTC, agatha197 commented
> If you run a session with accelerator set to 1 or higher, the session list does not reflect the accelerator.
> 
> ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/e9925eda-3306-4971-b460-3421ea58e022.png)

It is core issue. It will be handled in https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2682/fix-Remove-unused-device-gaudi-device.

2024-09-03 10:17 UTC, ironAiken2 approved these changes
LGTM

2024-09-03 10:53 UTC, merged