fix: content not showing up when scrolling horizontally
lablup/backend.ai-webui pull request #2627
Opened 2024-08-12 08:34 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-12 08:35 UTC, ironAiken2 commented
* **#2627** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2627?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-12 10:00 UTC, yomybaby requested changes
he title does not provide any indication of the affected component or page. Additionally, the description does not mention the current bug fixes. Please update the title and description accordingly.

2024-08-13 01:20 UTC, ironAiken2 commented
> he title does not provide any indication of the affected component or page. Additionally, the description does not mention the current bug fixes. Please update the title and description accordingly.

I apologize for the lack of clarification. I've fixed it.

2024-08-13 02:17 UTC, yomybaby approved these changes
LGTM

2024-08-13 02:19 UTC, merged