fix: revoke shared folder permission doesn't work
lablup/backend.ai-webui pull request #2644
Opened 2024-08-19 15:55 UTC by agatha197

resolves #2545

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-19 15:56 UTC, agatha197 commented
* **#2644** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2644?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-20 03:20 UTC, yomybaby requested changes

2024-08-20 03:20 UTC, yomybaby commented on src/components/backend-ai-storage-list.ts
> +      globalThis.backendaiclient.vfolder.leave(
Please check if the `/leave` API is for kicking out. I received an error message as follows:
```
{
    "type": "https://api.backend.ai/probs/insufficient-privilege",
    "title": "Insufficient privilege.",
    "msg": "Insufficient permission."
}
```

2024-08-22 03:45 UTC, gahyuun approved these changes

2024-08-23 02:57 UTC, yomybaby approved these changes
LGTM

2024-08-23 03:00 UTC, merged