fix: Windows architecture mismatch issue when downloading the app.
lablup/backend.ai-webui pull request #2649
Opened 2024-08-21 10:11 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-21 10:11 UTC, agatha197 commented
* **#2649** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2649?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-22 10:41 UTC, yomybaby requested changes
`SummaryItemDownloadApp` is not used yet, but it needs to be modified in [this part](https://github.com/lablup/backend.ai-webui/blob/e81d8679a1893ce2670ffb2c41b73381c9d4d908/react/src/components/SummaryPageItems/SummaryItemDownloadApp.tsx#L32-L33) as well.

2024-08-23 02:38 UTC, ironAiken2 commented on src/lib/backend.ai-client-esm.ts
> +    }
I think it's supposed to use win32 from version 23.09.5 onwards, but this part seems to work in reverse.

2024-08-23 02:41 UTC, ironAiken2 approved these changes
LGTM

2024-08-23 02:48 UTC, ironAiken2 requested changes
.

2024-08-23 05:45 UTC, ironAiken2 approved these changes
LGTM!

2024-08-23 05:54 UTC, yomybaby approved these changes
LGTM

2024-08-23 05:56 UTC, merged