fix: Consider folder state for vfolder invitations
lablup/backend.ai-webui pull request #2667
Opened 2024-08-29 04:38 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-08-29 04:38 UTC, ironAiken2 commented
* **#2667** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2667?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-29 07:20 UTC, gahyuun requested changes

2024-08-29 07:20 UTC, gahyuun commented on e2e/vfolder.test.ts
> +    await createVFolderAndVerify(page, 'e2e-rename-test-folder');await page.getByLabel('create', { exact: true }).click();
`await page.getByLabel('create', { exact: true }).click();`
This code occurs errors when I have multiple folders
`   Error: strict mode violation: getByLabel('create', { exact: true }) resolved to 2 elements:`

2024-08-29 07:20 UTC, gahyuun commented on e2e/vfolder.test.ts
> +    await page2.getByLabel('Accept').click();
`await page2.getByLabel('Accept').click();`
This code occurs errors when I have multiple folders
   Error: strict mode violation: getByLabel('Accept') resolved to 2 elements:

2024-08-30 02:55 UTC, gahyuun requested changes
Adding the `page.waitForTimeout(3000);` to `deleteVFolderAndVerify` seems to always succeed. 
  
```
...
  await page.locator('#delete-without-confirm-button').getByLabel('delete').click();
  await page.waitForTimeout(3000);
...
```

2024-08-30 02:55 UTC, gahyuun commented on e2e/vfolder.test.ts
> +    expect(page1.getByTitle('Invitation').locator('#activity').nth(0));
That code seems finds the element but doesn't validate any conditions like `toBeVisible`.
Also when there are multiple invitations, `nth(0)` seems to be a different folder invitation than e2e-share-test-folder.

2024-09-20 06:44 UTC, lizable requested changes
LGTM.

2024-09-20 06:44 UTC, lizable approved these changes
LGTM.

2024-09-27 05:10 UTC, merged