fix: modification of "model service's resource"
lablup/backend.ai-webui pull request #2687
Opened 2024-09-04 08:47 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-09-04 08:48 UTC, yomybaby commented
* **#2687** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2687?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-04 10:07 UTC, ironAiken2 requested changes
It works fine, but it seems like there needs to be some consideration for when the maximum quota for a resource group has changed.

[If the maximum allocatable amount is reduced by a resource policy from what it was before].
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/6e66790a-71fb-4bab-ac53-b9de31f8bf5b.png)

2024-09-04 10:32 UTC, yomybaby commented
In that case, the user must change the value to be smaller than the slider max. Is the current behavior not like that?

2024-09-05 02:32 UTC, ironAiken2 requested changes
Yes, that's how the behavior is implemented now. 

However, if the user doesn't modify the resource, the request can be sent with an existing set value (greater than the resource policy).

and please resolve the conflict!

2024-09-05 04:53 UTC, ironAiken2 approved these changes
LGTM

2024-09-05 05:30 UTC, merged