feat: import and start service from hugging face
lablup/backend.ai-webui pull request #2713
Opened 2024-09-20 06:59 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-09-20 06:59 UTC, agatha197 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2713?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2713** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2713?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2710** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2710?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2709** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2709?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2514** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-21 23:47 UTC, yomybaby requested changes
Opening the folder for Notification is only available when the current WebUI project is "model-store", otherwise it will throw an error. The reason is that the imported folder is a  "project" folder of "model-store" project.

2024-09-21 23:47 UTC, yomybaby commented on react/src/components/ImportFromHuggingFaceModal.tsx
>          onRequestClose();
Please handle `onRequestClose` after the mutation is finished.
Also please set the  submit button's loading prop to mutation's `isPending`

2024-09-21 23:52 UTC, yomybaby requested changes

2024-09-21 23:52 UTC, yomybaby commented on react/src/components/ImportFromHuggingFaceModal.tsx
> +                  message: `${t('data.modelStore.NewModelStoreFolderHasBeenCreated')}: ${data.folder.name}`,
You can use `description` too.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/c7e631a7-70d9-4c01-943c-86101ca5ad7f.png)

```suggestion
                  message: `${t('data.modelStore.NewModelStoreFolderHasBeenCreated')}`,
                  description: data.folder.name,
```

2024-09-30 03:07 UTC, agatha197 reviewed
handled with https://github.com/lablup/backend.ai-webui/pull/2717. close this issue.

2024-09-30 03:07 UTC, closed without merging