refactor: remove checking URL and add more form inputs
lablup/backend.ai-webui pull request #2714
Opened 2024-09-20 16:11 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-09-20 16:11 UTC, agatha197 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2714?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2713** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2713?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2714** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2714?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2710** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2710?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2709** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2709?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2514** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-20 22:20 UTC, yomybaby commented on react/src/components/ImportFromHuggingFaceModal.tsx
>    const [huggingFaceURL, setHuggingFaceURL] = useState<string | undefined>();
After removing URL checking, we can remove this.

2024-09-20 22:30 UTC, yomybaby requested changes
After removing URL checking, we can remove more code related to URL checking such as `huggingFaceURL` state,  `isPendingCheck` transition, `hugginFaceModelInfo` useUspenseTanQuery.

2024-09-20 22:34 UTC, yomybaby approved these changes
LGTM

2024-09-21 16:13 UTC, agatha197 reviewed
handled in https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2715/feat-Improve-form-item-and-switch-to-README-preview-on-validation-check

2024-09-21 16:13 UTC, closed without merging