fix: show/update supported AI accelerator based on selected environment in session launcher
lablup/backend.ai-webui pull request #2721
Opened 2024-09-25 09:47 UTC by lizable

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-09-25 09:48 UTC, lizable commented
* **#2721** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2721?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lizable and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-30 07:46 UTC, yomybaby requested changes
This PR modified `useResourceLimitAndRemaining`, but `resourceGroupResourceSize` and `remaining` in `useResourceLimitAndRemaining` are designed to provide information regardless of the currently selected image. Of course, `resourceLimits` is affected by the currently selected image. Could we try to resolve the issue without modifying `resourceGroupResourceSize` and `remaining`? @lizable

2024-09-30 13:59 UTC, yomybaby requested changes
After review and approve #2729, Please close this PR without merge.
Thank you.

2024-09-30 13:59 UTC, yomybaby commented on react/src/hooks/useResourceLimitAndRemaining.tsx
> +          ),
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines +295 to +338]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->This code works same as before because `_.min` ignore `undefined`. For example `_.min([8, 4, undefined])` is `4`.<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2721?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-10-08 05:52 UTC, yomybaby commented
I close this PR. Please check #2729

2024-10-08 05:52 UTC, closed without merging