feat: open folder explorer in vfolder table component and session launcher
lablup/backend.ai-webui pull request #2738
Opened 2024-10-07 09:37 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-10-07 09:37 UTC, ironAiken2 commented
* **#2738** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2738?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 02:00 UTC, yomybaby requested changes

2024-10-14 02:00 UTC, yomybaby commented on react/src/components/VFolderTable.tsx
> +  const { open } = useFolderExplorerOpener();
For readability, It would be better to rename it like this:
```suggestion
  const { open:openFolderExplorer } = useFolderExplorerOpener();
```

2024-10-14 02:00 UTC, yomybaby commented on react/src/components/VFolderTable.tsx
> +                      style={{ margin: 0 }}
Is there any reason to remove "alias path"?

2024-10-14 02:03 UTC, yomybaby requested changes
After reloading the page, all alias information disappears.

2024-10-14 02:42 UTC, ironAiken2 commented on react/src/components/VFolderTable.tsx
> +                      style={{ margin: 0 }}
No... My mistake. It should be included.

2024-10-14 04:12 UTC, ironAiken2 commented
> After reloading the page, all alias information disappears.

There seems to be some logic missing to add the existing settings on refresh.

`  useEffect(() => {
    if (aliasMap) {
      _.forEach(aliasMap, (v, k) => {
        internalForm.setFieldValue(
          k,
          aliasMap[k] && aliasMap[k]?.alias?.replace(aliasBasePath, ''),
        );
      });
    }
  }, [aliasMap, aliasBasePath, internalForm]);`

2024-10-14 04:13 UTC, ironAiken2 commented on react/src/components/VFolderTable.tsx
> -  }, [aliasMap, internalForm, aliasBasePath]);
`useEffect(() => {
    if (aliasMap) {
      _.forEach(aliasMap, (v, k) => {
        internalForm.setFieldValue(
          k,
          aliasMap[k] && aliasMap[k]?.alias?.replace(aliasBasePath, ''),
        );
      });
    }
  }, [aliasMap, aliasBasePath, internalForm]);`

2025-01-24 04:30 UTC, closed without merging