feat: recent session history
lablup/backend.ai-webui pull request #2742
Opened 2024-10-10 03:53 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-10-10 03:54 UTC, yomybaby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2742?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2742** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2742?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2741** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2741?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2740](https://github.com/lablup/backend.ai-webui/pull/2740) <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2740?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-16 04:53 UTC, agatha197 requested changes
Works fine. I just left minor comment to remove debugging codes.

2024-10-16 04:53 UTC, agatha197 commented on react/src/components/VFolderTableFormItem.tsx
> +  console.log(Form.useWatch('vfoldersAliasMap', form));
```suggestion
```

2024-10-16 04:53 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +      // { sessionName: '' } as Partial<SessionLauncherFormValue>,
```suggestion
```

2024-10-16 04:53 UTC, agatha197 commented on react/src/pages/SessionLauncherPage.tsx
> +              // console.log('##sessionPromises', firstSession);
```suggestion
```

2024-10-18 06:28 UTC, yomybaby commented
Thank you for reviewing. I have accepted your suggestion.

2024-10-21 05:16 UTC, lizable approved these changes
LGTM.

2024-10-21 06:22 UTC, agatha197 approved these changes
LGTM

2024-10-21 06:42 UTC, merged