feat: new image parsing
lablup/backend.ai-webui pull request #2785
Opened 2024-10-29 04:43 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-10-29 04:43 UTC, agatha197 commented
* **#2785** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2785?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-31 08:52 UTC, ironAiken2 commented on react/src/components/ImageList.tsx
> +              return requirementA.localeCompare(requirementB);
```suggestion
return localeCompare(requirementA, requirementB);
```

2024-10-31 08:56 UTC, ironAiken2 commented on react/src/components/ImageList.tsx
> +              return langA && langB ? langA.localeCompare(langB) : 0;
```suggestion
            return localeCompare(
                getLang(a.name ?? ''),
                getLang(b.name ?? ''),
              );
```

2024-10-31 08:57 UTC, ironAiken2 commented on react/src/components/ImageList.tsx
> +                : 0;
```suggestion
return localeCompare(getImageFullName(a), getImageFullName(b));
```

2024-10-31 09:00 UTC, ironAiken2 requested changes
It works fine but I left few small comments :)

2024-10-31 09:11 UTC, ironAiken2 commented on react/src/components/ImageList.tsx
> +    baiClient?.supports('extended-image-info') ?? false;
```suggestion
  const supportExtendedImageInfo =
    baiClient?.supports('extended-image-info');
```

2024-11-01 06:25 UTC, ironAiken2 approved these changes
(dismissed)

2024-11-01 07:05 UTC, ironAiken2 requested changes
Table Column name 을 대문자로 시작하도록 바꿔주세요.. 놓쳐서 죄송합니다. 

e.g.) `Full image path` -> `Full Image Path`

2024-11-01 08:39 UTC, yomybaby requested changes
Please check my suggestion.

2024-11-01 08:39 UTC, yomybaby commented on react/src/hooks/index.tsx
>      },
How about this suggestion for readability and less excuting Regexp test? 
```suggestion
      tagAlias: (tag: string) => {
        return (
          metadata?.tagAlias[tag] ??
          _.chain(metadata.tagReplace)
            .toPairs()
            .find(([regExpStr]) => new RegExp(regExpStr).test(tag))
            .thru((pair) => {
              if (pair) {
                const [regExpStr, replaceStr] = pair;
                return _.replace(tag, new RegExp(regExpStr), replaceStr);
              }
            })
            .value() ??
          _.startCase(tag)
        );
      },
    },
```

2024-11-04 02:32 UTC, yomybaby approved these changes
LGTM

2024-11-04 07:45 UTC, agatha197 commented
> Please change the Table Column name to start with an uppercase letter... sorry I missed it.
> 
> e.g.) `Full image path` -> `Full Image Path`

I followed Backend.AI Writing Rules 😉

2024-11-04 07:59 UTC, ironAiken2 approved these changes
LGTM

2024-11-05 09:54 UTC, merged