refactor: new image parsing on `CustomizedImageList`
lablup/backend.ai-webui pull request #2795
Opened 2024-10-31 03:33 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-10-31 03:33 UTC, agatha197 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2795?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2795** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2795?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2794** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2794?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2788** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2788?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2789** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2789?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2787** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2787?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2785** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2785?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-01 07:44 UTC, ironAiken2 commented on react/src/components/CustomizedImageList.tsx
> +  const [imageSearch, setImageSearch] = useState('');
It looks like you need imageSearch string based item filtering. 

[ref](https://github.com/lablup/backend.ai-webui/blob/188d31f8bd994635ee8e24dfc108663041a5d442/react/src/components/ImageList.tsx#L359-L394)

2024-11-01 07:47 UTC, ironAiken2 commented on react/src/components/CustomizedImageList.tsx
> +          </TextHighlighter>
Commented on [Previous Stack](https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2794/refactor-MyEnvironmentPage-into-two-components#comment-PRRC_kwDOCRTcws5szp4Z) about using the CopyButton component and the criteria for using copyable in Typography.Text.

2024-11-01 07:50 UTC, ironAiken2 commented on react/src/components/CustomizedImageList.tsx
> +              return langA && langB ? langA.localeCompare(langB) : 0;
```suggestion
              return localeCompare(langA, langB);
```

2024-11-01 07:51 UTC, ironAiken2 commented on react/src/components/CustomizedImageList.tsx
> +              return requirementA.localeCompare(requirementB);
```suggestion
              return localeCompare(requirementA, requirementB);
```

2024-11-01 07:53 UTC, ironAiken2 requested changes
I left some review about sorting and not being able to filter items based on search string.

2024-11-01 07:58 UTC, agatha197 commented on react/src/components/CustomizedImageList.tsx
> +          </TextHighlighter>
I was actually going to make a new thread to discuss about that :)

2024-11-04 07:43 UTC, yomybaby approved these changes
LGTM

2024-11-04 07:45 UTC, yomybaby approved these changes
LGTM

2024-11-05 10:45 UTC, merged