fix: show memory usage for each device in sessino list
lablup/backend.ai-webui pull request #2802
Opened 2024-11-01 02:17 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-01 02:17 UTC, ironAiken2 commented
* **#2802** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2802?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-01 03:01 UTC, agatha197 requested changes
Can you add `warboy.device`, `rngd.device`, and `hyperaccel-lpu.device` too?

2024-11-01 03:37 UTC, ironAiken2 commented
> Can you add `warboy.device`, `rngd.device`, and `hyperaccel-lpu.device` too?

I missed some... I'll add them now.

2024-11-04 09:08 UTC, agatha197 requested changes
hyperaccel-lpu.device memory is missed.

2024-11-05 09:39 UTC, ironAiken2 commented
> hyperaccel-lpu.device memory is missed.

4255~4276 line is about hyperaccel-lpu memory. @agatha197

2024-11-06 04:36 UTC, agatha197 approved these changes
LGTM

2024-11-06 04:43 UTC, merged