feat: batch session timeout
lablup/backend.ai-webui pull request #2824
Opened 2024-11-06 05:45 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-06 05:46 UTC, agatha197 commented
* **#2824** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2824?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-14 08:38 UTC, yomybaby requested changes

2024-11-14 08:38 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
> +                          </Flex>
`Form.Item` has `tooltip` prop. You don't need to add it in `label`

2024-11-14 08:38 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
> +                                    .humanize(true)
Using the `humanize` function does not provide an accurate duration, so it would be better to use an alternative way. How about `elapsedTime` of baiClient?

2024-11-14 08:38 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
> +                                  >
Please set `required` to true when `timeoutEnabled` is true.

2024-11-14 08:38 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
> +                            }
If `extra` is a React element, `Form.Item` creates a bottom space for it, which causes unnecessary space like this:

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/c2559aeb-b2a0-418e-9028-258ac51ea406.png)

We can change the hierarchy as shown below:
```jsx
<Form.Item shouldUpdate>
  <BAIIntervalView render={(text) => <Form.Item label="" extra={text} />}

2024-11-14 08:44 UTC, yomybaby commented on react/src/pages/SessionLauncherPage.tsx
> +                            }
We can use `dependencies={[['batch', 'timeoutEnabled'], ['batch', 'timeoutUnit']]}` instead of `shouldUpdate`

2024-11-14 09:47 UTC, yomybaby approved these changes
I push a commit to apply related to my reviews. LGTM, now!

2024-11-14 11:04 UTC, merged