add:  option to show/hide agent select option by launcher
lablup/backend.ai-webui pull request #2870
Opened 2024-11-21 08:36 UTC by lizable

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-21 08:37 UTC, lizable commented
* **#2870** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2870?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2870?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-21 09:45 UTC, yomybaby requested changes

2024-11-21 09:45 UTC, yomybaby commented on react/src/components/ResourceAllocationFormItems.tsx
> +      {!baiClient._config.hideAgents && enableAgentSelect && (
Let's move this condition to the `SessionLauncherPage` that uses this component.
```
<ResourceAllocationFormItems 
   enableAgentSelect={baiClient._config.hideAgents}/>
```
This change would simplify the ResourceAllocationFormItems component, making it more focused on state management, while also clarifying the control logic in the parent component.

2024-11-22 09:44 UTC, yomybaby commented on react/src/components/ResourceAllocationFormItems.tsx
>            required
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +1220]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->This is a screenshot when baiClient.supports('agent-select') is false and hideAgent=false.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/4a27d183-e293-449e-a71a-b88949bcc2ce.png)

Please consider this case.<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2870?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-11-22 09:45 UTC, yomybaby requested changes

2024-11-22 09:45 UTC, yomybaby commented on react/src/components/ResourceAllocationFormItems.tsx
>            required
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +1220]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->This is a screenshot when baiClient.supports('agent-select') is false and hideAgent=false.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/4a27d183-e293-449e-a71a-b88949bcc2ce.png)

Please consider this case.<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2870?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-11-25 09:28 UTC, yomybaby approved these changes
LGTM 🚢

2024-11-25 09:30 UTC, merged