add: draft for model player UI derived from WebUI
lablup/backend.ai-webui pull request #2878
Opened 2024-11-25 10:34 UTC by lizable

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-25 10:34 UTC, lizable commented
* **#2878** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2878?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2878?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-05-14 09:20 UTC, yomybaby requested changes

2025-05-14 09:20 UTC, yomybaby commented on src/backend-ai-app.ts
> +        '/model-store',
/mode-store already exists.

2025-05-14 09:20 UTC, yomybaby commented on src/components/backend-ai-error-view.ts
> +    globalThis.history.pushState({}, '', '/chat');
It should not be hardcoded to the chat.

2025-05-14 09:20 UTC, yomybaby commented on src/components/backend-ai-permission-denied-view.ts
> +    const page = url !== '' ? url : 'chat';
It should not be hardcoded to the chat.

2025-05-14 09:20 UTC, yomybaby commented on src/components/backend-ai-webui.ts
> +    'playground',
'playground' is not used any more, right?

2025-05-14 09:20 UTC, yomybaby commented on react/src/components/Chat/LLMChatCard.tsx
This file is already deleted in other PR. Please check and use alternative component.

2025-05-23 05:55 UTC, ragingwind commented on react/src/App.tsx
> +            // searchStringToObject: queryString.parse,
It looks useless comments. lets remove it

2025-05-23 05:56 UTC, yomybaby commented on react/src/components/ChatContent.tsx
> +const ChatContent: React.FC<ChatContentProps> = ({
It's better to rename this component because ChatContent feels like a content of chat message like `ChatMessageContent`.

2025-05-23 07:55 UTC, yomybaby commented on react/src/hooks/useBAINotification.tsx
> +    onResolve?: (notification: NotificationState) => void;
Please use the `resolved` and `rejected` property of `onChange` instead of adding `onResolve` and `onFailed.`

2025-05-23 07:59 UTC, yomybaby commented on react/src/pages/AIAgentPage.tsx
>            }}
Please use URLSearchParams for search parameters (link[https://github.com/lablup/backend.ai-webui/pull/3560/files#diff-e9da4ed7fd41d392e1a74ad4495f124f23f52ee62c4bca4ef3d299adb8fbb518R425-R431]).

2025-05-23 08:42 UTC, yomybaby commented on react/src/pages/ModelStoreListPage.tsx
>    const { styles } = useStyles();
Please delete if not in use.

2025-05-23 08:45 UTC, yomybaby commented on react/src/pages/ModelStoreListPage.tsx
> +      <ImportFromHuggingFacePanel />
All features that are exposed when not in PALI mode on the main branch should function correctly. Please remove this UI. If needed in PALI, ensure it is only visible in PALI mode.

2025-05-23 08:52 UTC, yomybaby commented on react/src/pages/ModelStorePage.tsx
Was it necessary to create the ModelStorePage? It would be better to use the ModelStoreListPage directly.

2025-05-23 08:55 UTC, yomybaby commented on react/src/pages/Page401.tsx
> +            onClick={() => webuiNavigate('/data')}
If you want to navigate `/data` instead of `/start` when PALI mode, please add redirect  it in browserRouter in App.tsx. ([ref](https://github.com/lablup/backend.ai-webui/blob/main/react/src/App.tsx#L190-L200))

2025-05-23 08:56 UTC, yomybaby commented on react/src/pages/Page404.tsx
> +            onClick={() => webuiNavigate('/data')}
If you want to navigate /data instead of /start when PALI mode, please add redirect it in browserRouter in App.tsx. (ref)

2025-05-28 05:54 UTC, lizable commented on react/src/components/ChatContent.tsx
> +  const conversation: ConversationType = {
@ragingwind I think we need to replace Conversation to Chat, since Conversation component will be removed.

2025-05-28 06:11 UTC, ragingwind commented on react/src/components/ChatContent.tsx
> +  const conversation: ConversationType = {
Conversation is gonna be removed in the PR for History. But you can make it with ChatCard. Here is pseudocode to use ChatCard for single Chat view
```
const ChatSinglePage = ({
  chat,
}: {
  chat: ChatData
}) => {
  const { styles } = useStyles();
  return (
    <Flex
      className={styles.chatViewVertical}
      direction="column"
      align="stretch"
      gap={'xs'}
    >
      <Flex
        className={styles.chatViewHorizontal}
        gap={'xs'}
        direction="row"
        align="stretch"
      >
        {_.map(chats, (chat, index) => (
          <ChatCard
            key={chat.id}
            className={styles.chatCard}
            chat={chat}
            closable={false}
            clonable={false)}
          />
        ))}
      </Flex>
    </Flex>
  );
};


// You can replace Conversation to SingleChatPage
const chat = createChat(provider)
<ChatSinglePage chat={chat} />
```

2025-09-19 02:36 UTC, closed without merging