refactor: new agent summary page
lablup/backend.ai-webui pull request #2882
Opened 2024-11-26 06:38 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-26 06:38 UTC, agatha197 commented
* **#2882** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2882?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2882?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-26 07:10 UTC, yomybaby requested changes

2024-11-26 07:10 UTC, yomybaby commented on react/src/components/AgentSummaryList.tsx
> +          </Flex>
It's better to use `colorSuccess` for `schedulable` and a disabled color for `schedulable === false`.
Currently, it's not easy to distinguish.
<img width="297" alt="image" src="https://github.com/user-attachments/assets/3b8940bb-601f-4c1f-a13a-7f29d638b9f7">

2024-11-27 01:26 UTC, yomybaby approved these changes
LGTM

2024-11-27 02:39 UTC, merged