refactor: Start page components
lablup/backend.ai-webui pull request #2885
Opened 2024-11-26 10:09 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-26 10:10 UTC, yomybaby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2885?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2885** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2885?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2885?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2786** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2786?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2661** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2661?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2851** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2851?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2853** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2853?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2850** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2850?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2847** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2847?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2846** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2846?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2858](https://github.com/lablup/backend.ai-webui/pull/2858) <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2858?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2844** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2844?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-02-26 06:32 UTC, ironAiken2 approved these changes
LGTM

2025-02-26 07:23 UTC, ironAiken2 requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/bc919bfa-e349-43a1-9a61-04a9fbdd095a.png)

There is an issue where the screen looks weird when scrolling. I'll fix it and commit it.@yomybaby

2025-02-26 08:00 UTC, ironAiken2 commented
Fixed ActionItemContent to have scrolling at the top (icon, description) except for the button. @yomybaby

2025-02-27 02:04 UTC, ironAiken2 approved these changes
LGTM

2025-02-27 04:43 UTC, merged