fix: switch to managing hiddenColumnKeys in TableColumnsSettingModal
lablup/backend.ai-webui pull request #2888
Opened 2024-11-27 04:56 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-11-27 04:56 UTC, agatha197 commented
* **#2888** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2888?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2888?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-27 07:00 UTC, yomybaby requested changes

2024-11-27 07:00 UTC, yomybaby commented on react/src/hooks/useBAISetting.tsx
>  }
This type can store only one setting.

```suggestion
[key: `hiddenColumnKeys.${string}`]: Array<string>;
}
```

Additionally, let's create a custom hook that can be used as follows:

```
const [hiddenColumKeys, setHiddenColumKeys] = useHiddenColumnKeysSetting('MyList');
```

```
type KnownSettingName = "MyList' | "AgentList";

const useHiddenColumnKeysSetting(listName:KnownSettingName) {
...
}

```

2024-11-27 23:02 UTC, agatha197 commented on react/src/hooks/useBAISetting.tsx
>  }
Thank you for the nice feedback! I reflected them.

2024-12-23 05:40 UTC, yomybaby approved these changes
I pushed a minor commit. LGTM 👍

2024-12-23 05:42 UTC, merged