bump: React 19 stable
lablup/backend.ai-webui pull request #2926
Opened 2024-12-09 03:28 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-09 03:28 UTC, yomybaby commented
* **#2926** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2926?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2926?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-24 05:09 UTC, ironAiken2 requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/70e38f4a-04af-4e32-ab64-81333ec804b5.png)

I've found an error, please check.

2025-01-24 05:09 UTC, ironAiken2 commented on react/src/index.tsx
> +import '@ant-design/v5-patch-for-react-19';
```suggestion
import '@ant-design/v5-patch-for-react-19';
```

2025-01-24 05:15 UTC, ironAiken2 commented
https://github.com/lablup/backend.ai-webui/blob/a48214d3c7460710e09d05b431f97e8b33ccb04c/react/src/components/ResourceAllocationFormItems.tsx#L1032-L1038

Please check this as well.

2025-01-24 10:52 UTC, yomybaby commented
@ironAiken2  Did you restart react dev server, after running `pnpm i`. Cloud you please check again? In my dev environment, there is no error.

2025-01-31 01:31 UTC, ironAiken2 commented
Yes the same thing happens if I delete `node_modules` also and restart the dev server after `pnpm i`.

@nowgnuesLee Can you please check this?

2025-01-31 01:46 UTC, nowgnuesLee commented
In my case, after running `pnpm i` and run server again, no errors appear.

2025-01-31 09:20 UTC, nowgnuesLee commented on react/src/components/ImageMetaIcon.tsx
>    border?: boolean;
Why would a border value be necessary if it’s not used in the code? Upon checking, it seems that the component’s usage doesn’t pass a border value either.

2025-01-31 09:26 UTC, nowgnuesLee commented on react/src/components/ImageTags.tsx
>    border?: boolean;
The `border` value is not being used here either. The `style` is declared but not applied.

2025-01-31 09:39 UTC, ironAiken2 approved these changes
LGTM!

2025-01-31 09:39 UTC, nowgnuesLee approved these changes
LGTM

2025-01-31 09:44 UTC, merged