feat: Session list NEO
lablup/backend.ai-webui pull request #2932
Opened 2024-12-10 04:21 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-10 04:22 UTC, yomybaby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2932?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2932** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2932?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2932?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2931** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2931?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-02-05 08:08 UTC, ironAiken2 approved these changes
LGTM

2025-02-05 08:08 UTC, ironAiken2 commented on react/src/components/ComputeSessionNodeItems/SessionStatusTag.tsx
> +        }}
The session status tag is also used in the session detail panel. If the style is changed, it will be inconsistent with the other tags in the detial panel.

2025-02-05 08:09 UTC, ironAiken2 requested changes
please refer 

https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2932/feat-FR-319-Session-list-NEO#comment-PRRC_kwDOCRTcws5zxnU1

2025-02-05 09:47 UTC, yomybaby commented on react/src/components/ComputeSessionNodeItems/SessionStatusTag.tsx
> +        }}
Okay, I'll comment out this part for now. Let's uncomment it later.

2025-02-05 10:34 UTC, ironAiken2 approved these changes
LGTM

2025-02-05 11:07 UTC, merged