feat: user list using `user_nodes` query
lablup/backend.ai-webui pull request #2934
Opened 2024-12-11 03:33 UTC by yomybaby

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-11 03:33 UTC, yomybaby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2934?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2934** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2934?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2934?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2757** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2757?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2 other dependent PRs ([#2755](https://github.com/lablup/backend.ai-webui/pull/2755) <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2755?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#2758](https://github.com/lablup/backend.ai-webui/pull/2758) <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2758?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#2754** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2754?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-12 09:04 UTC, agatha197 requested changes
1. I can't find the description even though the filtering supports the description.
2. In the role column, the superadmin is described as 'superadmin' but it is described as 'super admin' in filtering. Let's unify the expressions.
3. Please remove the USER | CREDENTIALS tab of the Credentials tab.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/16f6cfd2-238a-4665-9234-f31eb1d63200.png)

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/7a135e26-0506-4b6c-b388-12da9fdf7f29.png)

2024-12-12 09:04 UTC, agatha197 commented on react/src/pages/UserCredentialsPage.tsx
> +import UserNodeList from '../components/UserNodeList';
```suggestion
```

2024-12-12 09:04 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +        showSorterTooltip={false}
```suggestion
        showSorterTooltip={false}
        sortDirections={['descend', 'ascend', 'descend']}
```

2024-12-12 09:04 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +                      title={t('dialog.ask.DoYouWantToProceed')}
Let's use more direct message such as 'Delete user'.

2024-12-12 09:59 UTC, yomybaby commented
I'll check 1 & 2. 3 is handled in #2758

2024-12-13 03:11 UTC, yomybaby commented
Please check again. I resolve 1 and 2. Thank you

2024-12-13 03:13 UTC, yomybaby commented
I'll remove the USER | CREDENTIALS tab you mentioned so that the current PR can be merged first.

2024-12-13 03:16 UTC, agatha197 commented
I think 2 is not resolved yet.

2024-12-13 03:18 UTC, yomybaby commented
Sorry I don't know why it is reverted. I'll push again soon.

2024-12-13 03:19 UTC, agatha197 commented
And please check the unresolved threads too :)

2024-12-13 03:28 UTC, yomybaby commented on react/src/pages/UserCredentialsPage.tsx
> +import UserNodeList from '../components/UserNodeList';
You mean `UserList`, right? :) I deleted "Import UserList".

2024-12-13 05:19 UTC, agatha197 commented on react/src/pages/UserCredentialsPage.tsx
> +import UserNodeList from '../components/UserNodeList';
In previous version, it doesn't use UserNodeList. But it's not matter now.

2024-12-13 05:55 UTC, yomybaby commented on react/src/components/UserNodeList.tsx
> +                      title={t('dialog.ask.DoYouWantToProceed')}
I'll change the message because this action can be undone.

2024-12-13 12:45 UTC, agatha197 requested changes
I suggested color changes like other components.

2024-12-13 12:45 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +                    icon={<SettingOutlined />}
```suggestion
                    icon={<SettingOutlined style={{ color: token.colorInfo }} />}
```

2024-12-13 12:45 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +                      <InfoCircleOutlined style={{ color: token.colorInfo }} />
```suggestion
                      <InfoCircleOutlined style={{ color: token.colorSuccess }} />
```

2024-12-13 12:45 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +                      okType={isActive ? 'danger' : 'default'}
```suggestion
                      okType={isActive ? 'danger' : 'primary'}
```

2024-12-13 12:50 UTC, agatha197 requested changes

2024-12-13 12:50 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +import { UserNodeListDeleteMutation } from './__generated__/UserNodeListDeleteMutation.graphql';
```suggestion
```
It is defined but never used.

2024-12-13 12:50 UTC, agatha197 commented on react/src/components/UserNodeList.tsx
> +  DeleteOutlined,
```suggestion
```

2024-12-16 01:52 UTC, agatha197 approved these changes
LGTM!

2024-12-16 02:11 UTC, merged