feat: update `desired_session_count` field name to `replicas`
lablup/backend.ai-webui pull request #2963
Opened 2024-12-17 09:29 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2025-01-08 05:08 UTC, agatha197 requested changes

2025-01-08 05:08 UTC, agatha197 commented on react/src/pages/EndpointDetailPage.tsx
> +      children: endpoint?.desired_session_count ?? endpoint?.replicas,
Is there any reason to consider desired_session_count first? In `ServiceLauncherPageContent`, it uses replicas value first like `replicas: endpoint?.replicas ?? endpoint?.desired_session_count ?? 1,`

same as below.

2025-01-08 08:33 UTC, ironAiken2 commented on react/src/pages/EndpointDetailPage.tsx
> +      children: endpoint?.desired_session_count ?? endpoint?.replicas,
When `desired_session_count` deprecated since 24.12.0 and `replicas` supported since 24.12.0, it is unlikely that both values will come in at the same time.

But I think replicas should comes first because It's more recent fields and `desired_session_count` is for backward compatibility.

2025-01-09 01:18 UTC, agatha197 requested changes

2025-01-09 01:18 UTC, agatha197 commented on react/src/pages/EndpointListPage.tsx
> +                row?.desired_session_count ?? row?.replicas,
```suggestion
                row?.replicas ?? row?.desired_session_count,
```
I think so it's better to consider replicas first. Please apply it below similar codes too.

2025-01-10 10:34 UTC, yomybaby requested changes

2025-01-10 10:34 UTC, yomybaby commented on react/src/pages/EndpointDetailPage.tsx
> +  const navigate = useNavigate();
Is there any specific reason to use `useNavigate()`? If not, please use `webuiNavigate` instead.

2025-01-10 10:34 UTC, yomybaby commented on react/src/pages/EndpointDetailPage.tsx
> +                <span>{dayjs(row?.created_at).format('ll LT')}</span>
Row can not be `undefined`. Is there any reason to add `?.`?

2025-01-10 10:34 UTC, yomybaby commented on react/src/pages/EndpointListPage.tsx
> +                  setOptimisticDeletingId(row?.endpoint_id);
Same here, It can not be `undefined`

2025-01-10 10:34 UTC, yomybaby commented on react/src/pages/EndpointListPage.tsx
> +        dataSource={(modelServiceList?.items || []) as Endpoint[]}
Please use `filterNonNullItems` for `modelServiceList?.items`. and remove `as Endpoint[]`

2025-01-13 04:17 UTC, ironAiken2 commented on react/src/pages/EndpointDetailPage.tsx
> +  const navigate = useNavigate();
I've changed the order of the declarations in this section, and haven't added or deleted anything new. I was using navigate in the existing code, but I'll change that as well.

2025-01-13 04:40 UTC, ironAiken2 commented on react/src/pages/EndpointDetailPage.tsx
> +                <span>{dayjs(row?.created_at).format('ll LT')}</span>
I thought `created_at` should be null or undefined. I'll check query data type and apply optional chaining if have null or undefined value.

2025-01-13 04:40 UTC, ironAiken2 commented on react/src/pages/EndpointListPage.tsx
> +                  setOptimisticDeletingId(row?.endpoint_id);
https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2963/FR-17-feat-update-desired_session_count-field-name-to-replicas#comment-PRRC_kwDOCRTcws5yANWE

2025-01-13 05:28 UTC, ironAiken2 commented on react/src/pages/EndpointDetailPage.tsx
> +                <span>{dayjs(row?.created_at).format('ll LT')}</span>
Arrays for undefined or null are deleted when using filterNonNullItems, so rows can't be undefined. I'll fix this.

2025-01-13 08:22 UTC, yomybaby approved these changes
LGTM!

2025-01-14 02:01 UTC, agatha197 requested changes

2025-01-14 02:01 UTC, agatha197 commented on react/src/components/ServiceLauncherPageContent.tsx
> +                    label={t('modelService.NumberOfReplicas')}
Let's check `baiClient.supports('replicas')` for this too. Users can confused.

2025-01-14 02:01 UTC, agatha197 commented on react/src/pages/EndpointListPage.tsx
>        title: t('modelService.DesiredSessionCount'),
Same as above.

2025-01-14 02:39 UTC, ironAiken2 commented on react/src/components/ServiceLauncherPageContent.tsx
> +                    label={t('modelService.NumberOfReplicas')}
This field is also required for older versions that use desired_session_count.

2025-01-14 03:11 UTC, agatha197 requested changes

2025-01-14 03:11 UTC, agatha197 commented on react/src/components/ServiceLauncherPageContent.tsx
> +                    label={t('modelService.NumberOfReplicas')}
Then does it need to represent it to original text (desired session count)?

2025-01-14 07:46 UTC, agatha197 requested changes

2025-01-14 07:46 UTC, agatha197 commented on react/src/pages/EndpointListPage.tsx
> +    ...(baiClient.supports('replicas')
Please use `filterEmptyItem`

2025-01-14 08:51 UTC, ironAiken2 commented on react/src/pages/EndpointListPage.tsx
> +    ...(baiClient.supports('replicas')
This is used the same as desired_session_count, so I don't think it needs to be version specific.

2025-01-14 10:08 UTC, agatha197 commented on react/src/pages/EndpointListPage.tsx
> +    ...(baiClient.supports('replicas')
I just suggested this for better readability, but it's a minor issue so it doesn't need to be reflected.

2025-01-14 10:08 UTC, agatha197 approved these changes

2025-01-14 10:52 UTC, agatha197 approved these changes
LGTM 🚀

2025-01-14 10:54 UTC, merged