refactor: replace ChatInput with antdx component
lablup/backend.ai-webui pull request #2972
Opened 2024-12-20 06:59 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-20 07:00 UTC, agatha197 commented
* **#2972** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2972?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=2972).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-31 05:20 UTC, yomybaby requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/387993b1-24c2-4fae-a797-85c06eb7bd27.png)
Whe I enter
```
asdf
asdf
it displays like below:

2024-12-31 05:20 UTC, yomybaby commented on react/src/components/lablupTalkativotUI/ChatSender.tsx
> +      }}
The `Sender` component has an `onCancel` prop to handle the click event on the stop button.
```suggestion
        onSend && onSend();
      }}
      onCancel={() => {
        onStop && onStop();
      }}
```

2025-01-02 04:31 UTC, agatha197 commented
Applied.

2025-01-02 04:40 UTC, yomybaby approved these changes
LGTM

2025-01-02 04:45 UTC, merged