fix: set `Max Network Count` field to project resource policy
lablup/backend.ai-webui pull request #2989
Opened 2024-12-24 05:45 UTC by ironAiken2

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-24 05:45 UTC, ironAiken2 commented
* **#2989** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2989?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2989?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=2989).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-24 09:47 UTC, yomybaby requested changes
Please check version compatibility. I got a error on 24.09.3 manager.
```
{
    "data": null,
    "errors": [
        {
            "message": "Variable '$props' got invalid value {'max_vfolder_count': 0, 'max_quota_scope_size': -1, 'max_network_count': -1}; Field 'max_network_count' is not defined by type 'CreateProjectResourcePolicyInput'. Did you mean 'max_vfolder_count'?",
            "locations": [
                {
                    "line": 1,
                    "column": 74
                }
            ]
        }
    ]
}
```

2024-12-24 10:30 UTC, yomybaby requested changes

2024-12-24 10:30 UTC, yomybaby commented on react/src/components/ProjectResourcePolicySettingModal.tsx
> +          ...(baiClient.isManagerVersionCompatibleWith('24.12.0') && {
Please set the support checker to BAI client and use that.

2024-12-24 10:30 UTC, yomybaby commented on react/src/components/ProjectResourcePolicySettingModal.tsx
> +          ...(baiClient.isManagerVersionCompatibleWith('24.12.0') && {
This part is weird. A boolean cannot be spread. If the manager version is above 24.12.0, this can evaluate to false.

2024-12-26 07:19 UTC, lizable commented on react/src/components/ProjectResourcePolicyList.tsx
> +          render: (text) => (text === -1 ? '∞' : text),
I updated one line to display infinity symbol when the value is set to -1, which is regarded as unlimited, for better user experience.

2024-12-26 07:20 UTC, lizable approved these changes
LGTM.

2024-12-26 07:25 UTC, merged