feature: handle image in chat modal
lablup/backend.ai-webui pull request #2993
Opened 2024-12-30 07:52 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

2024-12-30 07:52 UTC, agatha197 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2993?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2993** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2993?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2993?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2972** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=2993).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-02 05:54 UTC, yomybaby requested changes
Could you set `getDropContainer` to enable users to drop files onto each chat card? Please refer https://x.ant.design/components/attachments#attachments-demo-basic

2025-01-02 07:51 UTC, agatha197 commented
Now it is available 🚀

2025-01-02 10:20 UTC, yomybaby requested changes
Please request a review again after improving the attachment UX.

2025-01-02 10:29 UTC, yomybaby approved these changes
LGTM

2025-01-02 10:31 UTC, merged